// A single history for the HTML body keeps structural photo edits, typing and
// browser formatting commands in their actual order. Metadata fields continue
// to use their own native input history.
export const editorHistoryScript = String.raw`
let editorUndoStates=[],editorUndoIndex=-1,editorUndoOwner=null,editorUndoPending=false,editorUndoApplying=false,editorComposing=false,editorHistorySerial=0,editorTyping=null;
function editorSelectionBookmark(){const range=bodyRange();if(!range)return null;const body=$('bodyHtml'),path=node=>{const indices=[];while(node&&node!==body){if(!node.parentNode)return null;indices.unshift(Array.prototype.indexOf.call(node.parentNode.childNodes,node));node=node.parentNode}return indices};return{start:path(range.startContainer),startOffset:range.startOffset,end:path(range.endContainer),endOffset:range.endOffset}}
function restoreEditorBookmark(bookmark){const body=$('bodyHtml');body.focus({preventScroll:true});const range=document.createRange(),resolve=path=>path?.reduce((node,index)=>node?.childNodes[index],body);try{const start=resolve(bookmark?.start),end=resolve(bookmark?.end);if(!start||!end)throw new Error();const length=node=>node.nodeType===3?node.textContent.length:node.childNodes.length;range.setStart(start,Math.min(bookmark.startOffset,length(start)));range.setEnd(end,Math.min(bookmark.endOffset,length(end)))}catch{range.selectNodeContents(body);range.collapse(false)}const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);captureFormatRange()}
function resetEditorHistory(){editorHistorySerial++;editorUndoOwner=current?.id;editorUndoStates=[{html:$('bodyHtml').innerHTML,selection:editorSelectionBookmark()}];editorUndoIndex=0;editorUndoPending=false;editorComposing=false;editorTyping=null}
function captureEditorBefore(){if(editorUndoApplying)return;if(editorUndoOwner!==current?.id)resetEditorHistory();const entry=editorUndoStates[editorUndoIndex];if(entry&&entry.html===$('bodyHtml').innerHTML)entry.selection=editorSelectionBookmark()}
function commitEditorHistory(){editorUndoPending=false;if(editorUndoApplying||editorComposing||!current)return;if(editorUndoOwner!==current.id){resetEditorHistory();return}const html=$('bodyHtml').innerHTML,previous=editorUndoStates[editorUndoIndex];if(previous?.html===html)return;const selection=editorSelectionBookmark(),now=Date.now(),merge=editorTyping&&editorTyping.merge&&previous?.typing===editorTyping.type&&now-previous.at<750&&editorUndoIndex===editorUndoStates.length-1;editorUndoStates.splice(editorUndoIndex+1);const entry={html,selection,typing:editorTyping?.type||null,at:now};if(merge)editorUndoStates[editorUndoIndex]=entry;else{editorUndoStates.push(entry);editorUndoIndex++}let bytes=editorUndoStates.reduce((sum,state)=>sum+state.html.length*2,0);while(editorUndoStates.length>2&&(editorUndoStates.length>80||bytes>24000000)){bytes-=editorUndoStates.shift().html.length*2;editorUndoIndex--}editorTyping=null}
function rememberEditorChange(){if(editorUndoApplying||editorComposing||editorUndoPending)return;editorUndoPending=true;const serial=editorHistorySerial;Promise.resolve().then(()=>{if(serial===editorHistorySerial)commitEditorHistory()})}
function editorHistoryCommand(command){if(busy||!current||editorComposing)return false;commitEditorHistory();const next=editorUndoIndex+(command==='undo'?-1:1);if(next<0||next>=editorUndoStates.length){status(command==='undo'?'실행 취소할 본문 변경이 없습니다.':'다시 실행할 본문 변경이 없습니다.');return false}editorUndoIndex=next;editorUndoApplying=true;try{clearMediaSelection();pendingFontSpans=null;pastedImageNodes=null;uploadRange=null;formatRange=null;$('bodyHtml').innerHTML=editorUndoStates[next].html;restoreEditorBookmark(editorUndoStates[next].selection);editorTyping=null;schedule();updateFormatState()}finally{editorUndoApplying=false}return true}
$('bodyHtml').addEventListener('beforeinput',event=>{if(editorComposing||event.isComposing)return;if(event.inputType==='historyUndo'||event.inputType==='historyRedo'){event.preventDefault();editorHistoryCommand(event.inputType==='historyUndo'?'undo':'redo');return}const previousSelection=editorUndoStates[editorUndoIndex]?.selection;captureEditorBefore();const type=event.inputType;if(['insertText','deleteContentBackward','deleteContentForward'].includes(type)&&!event.isComposing){const range=bodyRange();editorTyping={type,merge:!!range?.collapsed&&JSON.stringify(previousSelection)===JSON.stringify(editorSelectionBookmark())}}else editorTyping=null});
$('bodyHtml').addEventListener('input',rememberEditorChange);
$('bodyHtml').addEventListener('compositionstart',()=>{commitEditorHistory();captureEditorBefore();editorComposing=true;editorTyping=null});
$('bodyHtml').addEventListener('compositionend',()=>{editorComposing=false;editorTyping=null;rememberEditorChange()});
$('bodyHtml').addEventListener('keydown',event=>{if(editorComposing||event.isComposing)return;if((event.ctrlKey||event.metaKey)&&!event.altKey){const key=event.key.toLowerCase();if(key==='z'||key==='y'){event.preventDefault();event.stopImmediatePropagation();editorHistoryCommand(key==='y'||event.shiftKey?'redo':'undo')}}},true);
`;
