export const statisticsCss = `
.statistics-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:20px 0}.statistics-card{padding:16px;background:#f6f7f8;border-radius:6px;min-width:0}.statistics-card span{display:block;font-size:13px;color:#666}.statistics-card strong{display:block;font-size:28px;margin-top:8px;overflow-wrap:anywhere}.statistics-chart{height:160px;display:flex;align-items:end;gap:3px;padding:0;margin:24px 0 8px;list-style:none;border-bottom:1px solid #ccc}.statistics-chart li{flex:1;min-width:0;background:#386da8;position:relative}.statistics-chart li[data-zero=true]{background:#dce3eb}.statistics-axis{display:flex;justify-content:space-between;font-size:11px;color:#666;gap:8px}.statistics-table-wrap{overflow:auto;max-width:100%;margin:16px 0}.statistics-table{border-collapse:collapse;width:100%;font-size:13px}.statistics-table th,.statistics-table td{border-bottom:1px solid #e5e7e9;padding:10px 8px;text-align:right;font-variant-numeric:tabular-nums}.statistics-table th:first-child,.statistics-table td:first-child{text-align:left;overflow-wrap:anywhere}.statistics-table th{font-weight:600;white-space:nowrap}.statistics-table td:first-child{min-width:130px}.statistics-table td:not(:first-child){white-space:nowrap}.statistics-controls{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:16px 0}.statistics-controls input{flex:1;min-width:160px}.statistics-controls select{width:auto}.statistics-subheading{font-size:17px;margin:26px 0 10px}.statistics-period{font-size:13px;color:#666;line-height:1.7}.statistics-message{font-size:13px;line-height:1.7}.statistics-pagination{display:flex;align-items:center;justify-content:space-between;gap:10px}.statistics-pagination button{padding:8px 12px}@media(max-width:480px){.statistics-summary{gap:6px}.statistics-card{padding:12px 9px}.statistics-card strong{font-size:24px}.statistics-card span{font-size:12px}.statistics-chart{gap:2px}.statistics-table th,.statistics-table td{padding:9px 5px}.statistics-controls select{flex:1}}
`;

export const statisticsDialogHtml = `<dialog id="statisticsDialog" class="admin-dialog" aria-labelledby="statisticsTitle"><div class="dialog-heading"><h2 id="statisticsTitle">조회 통계</h2><button id="closeStatistics" type="button">닫기</button></div><p class="management-note">공개 글·페이지를 연 횟수를 집계하며 새로고침과 반복 열람도 포함합니다. 방문자 수(고유 인원)는 집계하지 않습니다. 이전 블로그 조회수는 가져오지 않으며, 모든 글은 이 사이트의 집계 시작 시점에 0부터 시작합니다.</p><div class="row"><button id="refreshStatistics" type="button">새로고침</button><span id="statisticsState" class="statistics-message" aria-live="polite"></span></div><p id="statisticsError" class="management-error" role="alert"></p><a id="statisticsLogin" href="/" target="_blank" rel="noopener" hidden>새 탭에서 로그인</a><div id="statisticsReport" hidden><p id="statisticsPeriod" class="statistics-period"></p><div class="statistics-summary"><div class="statistics-card"><span>오늘 조회수</span><strong id="statisticsToday"></strong></div><div class="statistics-card"><span>최근 30일 조회수</span><strong id="statisticsRecent"></strong></div><div class="statistics-card"><span>누적 조회수</span><strong id="statisticsTotal"></strong></div></div><h3 class="statistics-subheading">최근 30일 추이</h3><ol id="statisticsChart" class="statistics-chart" role="img" aria-label="날짜별 조회수 막대 그래프. 정확한 값은 날짜별 상세에서 확인할 수 있습니다."></ol><div id="statisticsAxis" class="statistics-axis" aria-hidden="true"></div><details><summary>날짜별 상세</summary><div class="statistics-table-wrap"><table class="statistics-table"><thead><tr><th scope="col">날짜</th><th scope="col">조회수</th></tr></thead><tbody id="statisticsDailyRows"></tbody></table></div></details><h3 class="statistics-subheading">글별 조회수</h3><div class="statistics-controls"><input id="statisticsSearch" type="search" aria-label="통계에서 글 찾기" placeholder="제목으로 찾기"><select id="statisticsSort" aria-label="글별 조회수 정렬"><option value="recent">최근 30일 조회수순</option><option value="total">누적 조회수순</option><option value="title">제목순</option></select></div><p id="statisticsPostCount" class="statistics-period" aria-live="polite"></p><div class="statistics-table-wrap"><table class="statistics-table"><thead><tr><th scope="col">글 제목</th><th scope="col">최근 30일</th><th scope="col">누적</th></tr></thead><tbody id="statisticsPostRows"></tbody></table></div><nav class="statistics-pagination" aria-label="글별 통계 페이지"><button id="statisticsPrevious" type="button">이전</button><span id="statisticsPage"></span><button id="statisticsNext" type="button">다음</button></nav></div></dialog>`;

export const statisticsScript = String.raw`
let statisticsData=null,statisticsBusy=false,statisticsPage=1,statisticsFetchedAt=null;
const statisticsNumber=value=>Number(value).toLocaleString('ko-KR');
function statisticsCell(tag,value){const cell=document.createElement(tag);cell.textContent=String(value);return cell}
function statisticsValidate(value){const count=n=>Number.isSafeInteger(n)&&n>=0,date=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s);if(!value||typeof value.timezone!=='string'||!date(value.startDate)||!date(value.endDate)||![value.todayViews,value.periodViews,value.totalViews].every(count)||!Array.isArray(value.daily)||!value.daily.every(row=>date(row.date)&&count(row.views))||!Array.isArray(value.posts)||!value.posts.every(row=>typeof row.id==='string'&&typeof row.title==='string'&&count(row.views)&&count(row.totalViews)))throw requestError('통계 응답을 확인하지 못했습니다. 새로고침을 눌러 다시 시도하세요.','invalid_response');try{new Intl.DateTimeFormat('ko-KR',{timeZone:value.timezone}).format(new Date())}catch{throw requestError('통계의 시간대 정보를 확인하지 못했습니다. 다시 시도하세요.','invalid_response')}return value}
function renderStatisticsPosts(){if(!statisticsData)return;const fragment=$('statisticsSearch').value.trim().toLocaleLowerCase('ko-KR'),sort=$('statisticsSort').value;const posts=statisticsData.posts.filter(post=>!fragment||post.title.toLocaleLowerCase('ko-KR').includes(fragment)).sort((a,b)=>(sort==='title'?a.title.localeCompare(b.title,'ko-KR'):(sort==='total'?b.totalViews-a.totalViews:b.views-a.views)||b.totalViews-a.totalViews||a.title.localeCompare(b.title,'ko-KR'))||a.id.localeCompare(b.id));const pages=Math.max(1,Math.ceil(posts.length/20));statisticsPage=Math.min(statisticsPage,pages);$('statisticsPostRows').replaceChildren();for(const post of posts.slice((statisticsPage-1)*20,statisticsPage*20)){const row=document.createElement('tr');row.append(statisticsCell('td',post.title||'제목 없음'),statisticsCell('td',statisticsNumber(post.views)),statisticsCell('td',statisticsNumber(post.totalViews)));$('statisticsPostRows').append(row)}if(!posts.length){const row=document.createElement('tr'),cell=statisticsCell('td',fragment?'찾는 제목이 없습니다.':'표시할 글이 없습니다.');cell.colSpan=3;row.append(cell);$('statisticsPostRows').append(row)}$('statisticsPostCount').textContent=posts.length+'개 · 조회수 0인 글도 포함합니다. 글·페이지·공지와 초안을 함께 표시합니다.';$('statisticsPage').textContent=statisticsPage+' / '+pages;$('statisticsPrevious').disabled=statisticsBusy||statisticsPage<=1;$('statisticsNext').disabled=statisticsBusy||statisticsPage>=pages}
function renderStatistics(){const data=statisticsData;if(!data)return;$('statisticsReport').hidden=false;$('statisticsToday').textContent=statisticsNumber(data.todayViews);$('statisticsRecent').textContent=statisticsNumber(data.periodViews);$('statisticsTotal').textContent=statisticsNumber(data.totalViews);$('statisticsPeriod').textContent='최근 30일: '+data.startDate+' ~ '+data.endDate+' (오늘 포함) · 날짜 집계 시간대: '+data.timezone+'. 날짜는 조회 당시 설정을 따르며, 시간대 변경 전 기록의 날짜는 이동하지 않습니다.';const daily=[...data.daily].sort((a,b)=>a.date.localeCompare(b.date)),max=Math.max(1,...daily.map(row=>row.views));$('statisticsChart').replaceChildren();$('statisticsDailyRows').replaceChildren();$('statisticsAxis').replaceChildren();for(const point of daily){const bar=document.createElement('li');bar.style.height=(point.views?Math.max(3,point.views/max*150):2)+'px';bar.dataset.zero=String(point.views===0);bar.title=point.date+': '+statisticsNumber(point.views)+'회';bar.setAttribute('aria-hidden','true');$('statisticsChart').append(bar);const row=document.createElement('tr');row.append(statisticsCell('td',point.date),statisticsCell('td',statisticsNumber(point.views)));$('statisticsDailyRows').append(row)}for(const point of [daily[0],daily[Math.floor((daily.length-1)/2)],daily.at(-1)].filter(Boolean))$('statisticsAxis').append(statisticsCell('span',point.date.slice(5)));renderStatisticsPosts()}
function setStatisticsBusy(value){statisticsBusy=value;$('refreshStatistics').disabled=value;$('statisticsSearch').disabled=value;$('statisticsSort').disabled=value;$('statisticsDialog').setAttribute('aria-busy',String(value));if(statisticsData)renderStatisticsPosts()}
async function loadStatistics(){if(statisticsBusy)return;setStatisticsBusy(true);$('statisticsState').textContent='통계 불러오는 중…';$('statisticsError').textContent='';$('statisticsLogin').hidden=true;try{const result=statisticsValidate(await api('/statistics'));statisticsData=result;statisticsFetchedAt=new Date();renderStatistics();$('statisticsState').textContent=statisticsFetchedAt.toLocaleString('ko-KR',{timeZone:result.timezone})+' 기준'}catch(error){$('statisticsError').textContent=error.message;$('statisticsLogin').hidden=error.code!=='authentication_required';$('statisticsState').textContent=statisticsData?'새로고침하지 못했습니다. 아래는 '+statisticsFetchedAt.toLocaleString('ko-KR',{timeZone:statisticsData.timezone})+'에 가져온 결과입니다.':'아직 통계를 가져오지 못했습니다.'}finally{setStatisticsBusy(false)}}
$('manageStatistics').onclick=async()=>{if(busy)return;clearMediaSelection();closeFormatPanels();$('statisticsDialog').showModal();await loadStatistics()};
$('closeStatistics').onclick=()=>{$('statisticsDialog').close();$('manageStatistics').focus({preventScroll:true})};
$('statisticsDialog').addEventListener('cancel',event=>{event.preventDefault();$('closeStatistics').onclick()});
$('refreshStatistics').onclick=loadStatistics;
$('statisticsSearch').oninput=()=>{statisticsPage=1;renderStatisticsPosts()};$('statisticsSort').onchange=()=>{statisticsPage=1;renderStatisticsPosts()};
$('statisticsPrevious').onclick=()=>{if(statisticsBusy||statisticsPage<=1)return;statisticsPage--;renderStatisticsPosts()};$('statisticsNext').onclick=()=>{if(statisticsBusy||!statisticsData)return;statisticsPage++;renderStatisticsPosts()};
`;
