export const extrasCss = `
.extra-menu{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.extra-menu button{text-align:left;font-size:13px}.extra-fields{display:grid;gap:12px}.extra-fields label{margin:0}.extra-fields textarea{min-height:180px}.extra-fields textarea.source-input{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;min-height:45vh;font-size:13px;line-height:1.6}.character-grid{display:flex;flex-wrap:wrap;gap:8px;margin:15px 0}.character-grid button{font-size:21px;min-width:42px}.shortcut-list{line-height:2;list-style:none;padding:0}.shortcut-list kbd{font-family:inherit;background:#f3f4f6;padding:3px 6px;border-radius:3px}.extra-note{font-size:13px;line-height:1.75;color:#777}.extra-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.table-position-options{display:flex;flex-wrap:wrap;gap:8px;border:0;margin:0;padding:0}.table-position-options legend{font-size:14px;margin-bottom:8px}.table-position-options button[aria-pressed="true"]{background:#e8f1ff;color:#145bac;border-color:#8bb5ee}.html-editor details{padding:12px;border:1px solid #ddd}.html-editor summary{cursor:pointer}.html-editor pre{padding:16px;overflow:auto;background:#f6f6f6}.html-editor pre code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.html-editor figure.alignLeft{margin-left:0;margin-right:auto}.html-editor figure.alignCenter{margin-inline:auto}.html-editor figure.alignRight{margin-left:auto;margin-right:0}@media(max-width:480px){.extra-menu{grid-template-columns:repeat(2,minmax(0,1fr))}.image-tools{gap:7px;padding:8px}.image-tools__label{max-width:110px;font-size:11px}.image-tools button{padding:8px;font-size:12px}}
`;
export const extrasToolbarHtml = `<div class="format-group"><select id="fontFamily" aria-label="글꼴"><option value="var(--dwnc-body-font)">기본 글꼴</option><option value="'나눔고딕', sans-serif">나눔고딕</option><option value="'나눔명조', serif">나눔명조</option><option value="Georgia, serif">명조</option><option value="monospace">고정폭</option><option value="current" disabled>현재 글꼴</option></select><button id="moreTools" type="button" title="추가 편집 도구" aria-expanded="false">더보기 ▾</button></div>`;
export const extrasHtml = `<div id="extraMenu" class="format-panel extra-menu" hidden><button type="button" data-extra-mode="removeFormat">글자 서식 지우기</button><button type="button" data-extra-mode="code">코드 블록</button><button type="button" data-extra-mode="details">접은 글</button><button type="button" data-extra-mode="characters">특수문자</button><button type="button" data-extra-mode="card">링크 카드</button><button type="button" data-extra-mode="table">표 편집</button><button type="button" data-extra-mode="html">HTML 편집</button><button type="button" data-extra-mode="shortcuts">단축키 안내</button></div><dialog id="extraDialog" class="admin-dialog" aria-labelledby="extraTitle"><div class="dialog-heading"><h2 id="extraTitle"></h2><button id="closeExtra" type="button">닫기</button></div><div id="extraContent" class="extra-fields"></div><p id="extraError" class="management-error" role="alert"></p><a id="extraLogin" href="/" target="_blank" rel="noopener" hidden>새 탭에서 로그인한 뒤 적용을 다시 누르세요.</a><div class="extra-actions"><button id="applyExtra" class="publish" type="button">적용</button></div></dialog>`;

export const extrasScript = String.raw`
let extraMode=null,extraTarget=null,extraBusy=false,extraReturn=null,extraImageWidthChanged=false,extraImageAlignChanged=false;
function closeExtraMenu(){$('extraMenu').hidden=true;$('moreTools').setAttribute('aria-expanded','false')}
function extraField(id,label,value='',type='text'){const wrapper=document.createElement('label');wrapper.textContent=label;const input=document.createElement(type==='textarea'?'textarea':'input');input.id=id;if(type!=='textarea')input.type=type;input.value=value;wrapper.append(input);$('extraContent').append(wrapper);return input}
function extraNote(text){const note=document.createElement('p');note.className='extra-note';note.textContent=text;$('extraContent').append(note)}
function extraSelect(id,label,options,value){const wrapper=document.createElement('label');wrapper.textContent=label;const select=document.createElement('select');select.id=id;for(const [key,text] of options){const option=document.createElement('option');option.value=key;option.textContent=text;select.append(option)}select.value=value;wrapper.append(select);$('extraContent').append(wrapper);return select}
function bodyCell(){const range=bodyRange()||formatRange,element=range&&(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement);const cell=element?.closest('td,th');return cell&&$('bodyHtml').contains(cell)?cell:null}
function selectedCard(){const range=bodyRange()||formatRange,element=range&&(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement);const card=selectedMedia?.kind==='link-card'?selectedMedia.node:element?.closest('figure[data-ke-type="opengraph"],.se_component.se_oglink,.se-component.se-oglink');return card&&$('bodyHtml').contains(card)?card:null}
function openExtra(mode,target=null){if(busy||!current)return;captureFormatRange();if(mode==='removeFormat'){closeExtraMenu();formatCommand('removeFormat');return}if(selectedMedia&&!['image','card'].includes(mode)){status('먼저 서식을 바꿀 본문 글자를 선택하세요.');return}extraReturn=document.activeElement;extraMode=mode;extraTarget=target||(mode==='card'?selectedCard():mode==='table'?bodyCell():null);closeExtraMenu();closeFormatPanels();$('uploadPanel').hidden=true;$('extraContent').replaceChildren();$('extraError').textContent='';$('extraLogin').hidden=true;$('applyExtra').hidden=['characters','shortcuts','table'].includes(mode);const selection=formatRange?.toString()||'';const titles={code:'코드 블록',details:'접은 글',characters:'특수문자',card:extraTarget?'링크 카드 수정':'링크 카드',image:'사진 편집',table:'표 편집',html:'HTML 편집',shortcuts:'단축키 안내'};$('extraTitle').textContent=titles[mode];
if(mode==='code')extraField('extraText','코드',selection,'textarea').className='source-input';
if(mode==='details'){extraField('extraSummary','접힌 상태에 표시할 글자','더 보기');extraField('extraText','펼치면 표시할 내용',selection,'textarea')}
if(mode==='characters'){const grid=document.createElement('div');grid.className='character-grid';for(const character of ['©','®','™','°','℃','±','×','÷','≠','≤','≥','∞','→','←','↑','↓','✓','★','☆','•','…','※','①','②','③','④','⑤','♥','☑','□','〈','〉','「','」']){const button=document.createElement('button');button.type='button';button.textContent=character;button.onclick=()=>{closeExtraDialog(false);formatCommand('insertText',character)};grid.append(button)}$('extraContent').append(grid)}
if(mode==='card'){const link=extraTarget?.querySelector('a');extraField('extraUrl','링크 주소',link?.getAttribute('href')||'','url');extraField('extraCardTitle','제목',extraTarget?.querySelector('.og-title,.se-oglink-title')?.textContent||selection);extraField('extraDescription','설명',extraTarget?.querySelector('.og-desc,.se-oglink-summary')?.textContent||'','textarea');extraField('extraImage','사진 주소 (선택)',extraTarget?.querySelector('img')?.getAttribute('src')||'');extraNote('사진은 이 블로그에 첨부한 /media/... 주소를 사용할 수 있습니다. 비워 두면 글자로 된 카드를 넣습니다.')}
if(mode==='image'){extraImageWidthChanged=false;extraImageAlignChanged=false;const image=extraTarget?.querySelector('img')||(extraTarget?.tagName==='IMG'?extraTarget:null);if(!image){status('사진을 선택한 뒤 다시 눌러 주세요.');return}extraField('extraAlt','사진 대체텍스트',image.getAttribute('alt')||'');extraField('extraCaption','사진 아래 설명',extraTarget.querySelector('figcaption,.se-caption,.se_mediaCaption')?.textContent||'');extraSelect('extraAlign','사진 정렬',[['left','왼쪽'],['center','가운데'],['right','오른쪽']],extraTarget.classList.contains('alignRight')?'right':extraTarget.classList.contains('alignLeft')?'left':'center').onchange=()=>{extraImageAlignChanged=true};const size=extraField('extraWidth','본문 너비 대비 크기 (%)',String(extraTarget.style.width?.endsWith('%')?parseFloat(extraTarget.style.width):100),'number');size.min='10';size.max='100';size.oninput=()=>{extraImageWidthChanged=true};extraNote('사진 원본은 그대로 두고 본문에 표시하는 크기와 설명만 바꿉니다.')}
if(mode==='html'){extraField('extraText','본문 HTML',$('bodyHtml').innerHTML,'textarea').className='source-input';extraNote('지원하지 않는 코드와 위험한 속성은 적용할 때 정리됩니다. 적용 뒤 실행 취소로 돌아갈 수 있습니다.')}
if(mode==='shortcuts'){const list=document.createElement('ul');list.className='shortcut-list';for(const [keys,text] of [['⌘ / Ctrl + B','굵게'],['⌘ / Ctrl + I','기울임'],['⌘ / Ctrl + U','밑줄'],['⌘ / Ctrl + K','링크 삽입·수정'],['⌘ / Ctrl + Z','실행 취소'],['⌘ / Ctrl + Shift + Z','다시 실행'],['Tab / Shift + Tab','표의 다음 / 이전 셀'],['Delete / Backspace','선택한 사진·링크 카드 삭제'],['Esc','열린 도구나 미리보기 닫기']]){const item=document.createElement('li'),kbd=document.createElement('kbd');kbd.textContent=keys;item.append(kbd,' — '+text);list.append(item)}$('extraContent').append(list)}
if(mode==='table'){if(!extraTarget){extraNote('표의 셀 안에 커서를 놓고 다시 열어 주세요.')}else{const table=extraTarget.closest('table'),merged=Array.from(table.querySelectorAll('td,th')).some(cell=>cell.colSpan>1||cell.rowSpan>1);const positions=document.createElement('fieldset'),legend=document.createElement('legend');positions.className='table-position-options';legend.textContent='표 위치';positions.append(legend);for(const [value,label] of [['left','왼쪽'],['center','가운데'],['right','오른쪽']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.dataset.tablePosition=value;button.setAttribute('aria-pressed',String(tablePosition(table)===value));button.onclick=()=>setTablePosition(value);positions.append(button)}$('extraContent').append(positions);extraNote('표 전체를 본문 영역의 왼쪽·가운데·오른쪽에 놓습니다. 셀 안의 글자 정렬은 바꾸지 않습니다. 본문 폭을 모두 쓰는 표는 위치 차이가 보이지 않을 수 있습니다.');extraNote('현재 셀을 기준으로 편집합니다. 병합된 표는 구조를 보호하기 위해 일부 행·열 작업을 제한합니다.');for(const [cmd,label] of [['rowBefore','위에 행 추가'],['rowAfter','아래에 행 추가'],['columnBefore','왼쪽에 열 추가'],['columnAfter','오른쪽에 열 추가'],['removeRow','현재 행 삭제'],['removeColumn','현재 열 삭제'],['mergeRight','오른쪽 셀과 병합'],['split','셀 나누기']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.disabled=merged&&!['mergeRight','split'].includes(cmd);button.onclick=()=>editTable(cmd);$('extraContent').append(button)}}}
$('extraDialog').showModal();$('extraContent').querySelector('input,textarea,select,button')?.focus()}
function closeExtraDialog(restore=true){if(extraBusy)return;$('extraDialog').close();if(restore){if(extraTarget&&$('bodyHtml').contains(extraTarget)){clearMediaSelection();restoreFormatRange()}else restoreFormatRange()}}
$('closeExtra').onclick=()=>closeExtraDialog();$('extraDialog').addEventListener('cancel',event=>{event.preventDefault();closeExtraDialog()});
$('moreTools').addEventListener('mousedown',event=>event.preventDefault());$('moreTools').onclick=()=>{if(busy)return;captureFormatRange();const opening=$('extraMenu').hidden;closeFormatPanels();$('uploadPanel').hidden=true;$('extraMenu').hidden=!opening;$('moreTools').setAttribute('aria-expanded',String(opening))};for(const button of $('extraMenu').querySelectorAll('[data-extra-mode]')){button.addEventListener('mousedown',event=>event.preventDefault());button.onclick=()=>openExtra(button.dataset.extraMode)}
$('fontFamily').addEventListener('pointerdown',captureFormatRange);$('fontFamily').onchange=()=>{if($('fontFamily').value!=='current')formatCommand('fontName',$('fontFamily').value)};
document.addEventListener('selectionchange',()=>{const range=bodyRange();if(!range)return;const element=range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement;if(!element)return;const actual=window.getComputedStyle(element).fontFamily.toLowerCase().replaceAll('"',"'");const basic=window.getComputedStyle($('bodyHtml')).fontFamily.toLowerCase().replaceAll('"',"'");const option=Array.from($('fontFamily').options).find(option=>option.value!=='current'&&actual.includes(option.value.split(',')[0].toLowerCase().replaceAll('"',"'")));$('fontFamily').value=actual===basic?'var(--dwnc-body-font)':option?.value||'current'});
// Whole-document HTML is not a rich-text insertion: execCommand can retain the
// first selected block/inline ancestors and nest the replacement inside them.
// Use the editor's own history, which already restores complete innerHTML.
function replaceEditorHtml(html){if(busy||!current)return false;commitEditorHistory();captureEditorBefore();editorTyping=null;clearMediaSelection();pendingFontSpans=null;pastedImageNodes=null;uploadRange=null;formatRange=null;$('bodyHtml').innerHTML=html;if(typeof resetAutoLinks==='function')resetAutoLinks();restoreEditorBookmark(null);schedule();updateFormatState();return true}
// An existing block must be replaced as a node, not inserted as rich text:
// execCommand can retain its figure ancestor and wrap every subsequent edit.
function replaceExtraTarget(html){
  if(busy||!current||editorComposing)return false;
  const body=$('bodyHtml');if(!extraTarget||!body.contains(extraTarget))throw new Error('편집할 항목이 본문에 없습니다. 다시 선택해 주세요.');
  const range=document.createRange();range.selectNode(extraTarget);const fragment=range.createContextualFragment(html),last=fragment.lastChild;if(!last)return false;
  const before=body.innerHTML;commitEditorHistory();captureEditorBefore();editorTyping=null;
  clearMediaSelection();pendingFontSpans=null;pastedImageNodes=null;uploadRange=null;formatRange=null;
  extraTarget.replaceWith(fragment);
  body.focus({preventScroll:true});const caret=document.createRange();
  if(extraMode==='image'||extraMode==='card'){
    // Resume ordinary text outside the complete photo/group, including any
    // pre-existing wrappers. Reuse the following paragraph on repeated edits.
    let boundary=last;
    for(let parent=last.parentElement;parent&&parent!==body;parent=parent.parentElement)if(parent.matches('figure,.dwnc-image-layout,.se_component.se_image,.se-component.se-image,.se_component.se_oglink,.se-component.se-oglink'))boundary=parent;
    if(boundary.matches?.('figure,.dwnc-image-layout,.se_component.se_image,.se-component.se-image,.se_component.se_oglink,.se-component.se-oglink')){
      let paragraph=boundary.nextElementSibling;
      if(!paragraph?.matches('p')||paragraph.querySelector('img,video,audio,iframe,table,hr')){paragraph=document.createElement('p');paragraph.append(document.createElement('br'));boundary.after(paragraph)}
      caret.selectNodeContents(paragraph);caret.collapse(true);
    }else{caret.setStartAfter(last);caret.collapse(true)}
  }else{const cell=last.querySelector?.('td,th');if(cell)caret.selectNodeContents(cell);else caret.setStartAfter(last);caret.collapse(true)}
  const selection=window.getSelection();selection.removeAllRanges();selection.addRange(caret);captureFormatRange();updateFormatState();
  if(body.innerHTML!==before)schedule();return true;
}
function tablePosition(table){const left=table.style.getPropertyValue('margin-left'),right=table.style.getPropertyValue('margin-right');if(left==='auto')return right==='auto'?'center':'right';if(right==='auto')return'left';const align=table.getAttribute('align');return['left','center','right'].includes(align)?align:'left'}
function setTablePosition(position){
  if(busy||extraBusy||!current||editorComposing||!['left','center','right'].includes(position))return false;
  const table=extraTarget?.closest('table');if(!table||!$('bodyHtml').contains(table))return false;
  const before=table.outerHTML;commitEditorHistory();captureEditorBefore();editorTyping=null;
  table.classList.add('dwnc-table-positioned');table.removeAttribute('align');
  for(const property of ['float','margin-inline','margin-inline-start','margin-inline-end'])table.style.removeProperty(property);
  table.style.setProperty('margin-left',position==='left'?'0':'auto','important');table.style.setProperty('margin-right',position==='right'?'0':'auto','important');
  for(const button of $('extraContent').querySelectorAll('[data-table-position]'))button.setAttribute('aria-pressed',String(button.dataset.tablePosition===position));
  if(table.outerHTML!==before){pendingFontSpans=null;pastedImageNodes=null;schedule();status('표 위치를 바꿨습니다. 셀 안의 글자 정렬은 유지하며 작업본에 자동저장됩니다.')}
  return true;
}
function editTable(command){try{const originalCell=extraTarget,original=originalCell.closest('table'),table=original.cloneNode(true),rowIndex=Array.from(original.rows).indexOf(originalCell.parentElement),cellIndex=Array.from(originalCell.parentElement.cells).indexOf(originalCell),row=table.rows[rowIndex],cell=row.cells[cellIndex];if(command==='mergeRight'){const next=cell.nextElementSibling;if(!next||cell.rowSpan!==1||next.rowSpan!==1)throw new Error('같은 행의 오른쪽 셀과 병합할 수 없습니다.');cell.colSpan+=next.colSpan;cell.append(document.createElement('br'),...Array.from(next.childNodes));next.remove()}else if(command==='split'){if(cell.rowSpan!==1||cell.colSpan<=1)throw new Error('가로로 병합한 셀에서 사용할 수 있습니다.');const columns=cell.colSpan;cell.colSpan=1;for(let i=1;i<columns;i++){const added=document.createElement(cell.tagName.toLowerCase());added.append(document.createElement('br'));cell.after(added)}}else{if(Array.from(table.querySelectorAll('td,th')).some(c=>c.rowSpan>1||c.colSpan>1))throw new Error('병합된 셀을 먼저 나누어 주세요.');if(command.startsWith('row')){const added=document.createElement('tr');for(const old of row.cells){const td=document.createElement(old.tagName.toLowerCase());td.append(document.createElement('br'));added.append(td)}if(command==='rowBefore')row.before(added);else row.after(added)}else if(command.startsWith('column')){for(const r of table.rows){const td=document.createElement(r.cells[cellIndex].tagName.toLowerCase());td.append(document.createElement('br'));if(command==='columnBefore')r.cells[cellIndex].before(td);else r.cells[cellIndex].after(td)}}else if(command==='removeRow'){if(table.rows.length<=1)throw new Error('마지막 행은 삭제할 수 없습니다.');row.remove()}else if(command==='removeColumn'){if(row.cells.length<=1)throw new Error('마지막 열은 삭제할 수 없습니다.');for(const r of table.rows)r.cells[cellIndex].remove()}}extraTarget=original;closeExtraDialog(false);replaceExtraTarget(table.outerHTML)}catch(error){$('extraError').textContent=error.message}}
$('applyExtra').onclick=async()=>{if(extraBusy||busy)return;try{let html='';const text=()=>escapeFormatText($('extraText').value);if(extraMode==='code')html='<pre><code>'+text()+'</code></pre><p><br></p>';if(extraMode==='details')html='<details><summary>'+escapeFormatText($('extraSummary').value||'더 보기')+'</summary><p>'+text().replaceAll('\n','<br>')+'</p></details><p><br></p>';if(extraMode==='card'){const href=$('extraUrl').value.trim(),title=$('extraCardTitle').value.trim(),src=$('extraImage').value.trim();if(!validLink(href)||!title)throw new Error('링크 주소와 카드 제목을 입력하세요.');if(src&&(!src.startsWith('/media/')||src.includes('?')||src.includes('#')||src.includes('..')))throw new Error('이 블로그에 첨부한 /media/... 사진 주소를 입력하거나 비워 주세요.');let host='';try{host=new URL(href,'https://dwnc.me').hostname}catch{}html='<figure data-ke-type="opengraph" contenteditable="false" data-editor-inserted-card="true"><a href="'+escapeFormatText(href)+'" target="_blank" rel="noopener noreferrer">'+(src?'<span class="og-image"><img src="'+escapeFormatText(src)+'" alt=""></span>':'')+'<span class="og-text"><span class="og-title">'+escapeFormatText(title)+'</span><span class="og-desc">'+escapeFormatText($('extraDescription').value)+'</span><span class="og-host">'+escapeFormatText(host)+'</span></span></a></figure>'+(extraTarget?'':'<p><br></p>')}
if(extraMode==='image'){const copy=extraTarget.cloneNode(true),image=copy.querySelector('img')||(copy.tagName==='IMG'?copy:null),width=Number($('extraWidth').value);if(!image||extraImageWidthChanged&&(!Number.isFinite(width)||width<10||width>100))throw new Error('사진 크기는 10부터 100 사이로 입력하세요.');image.setAttribute('alt',$('extraAlt').value.trim());let figure=copy;if(copy.tagName==='IMG'&&($('extraCaption').value.trim()||extraImageAlignChanged||extraImageWidthChanged)){figure=document.createElement('figure');figure.className='imageblock';figure.append(copy)}if(extraImageAlignChanged){figure.classList.remove('alignLeft','alignCenter','alignRight');figure.classList.add({left:'alignLeft',center:'alignCenter',right:'alignRight'}[$('extraAlign').value]);figure.style.marginLeft=$('extraAlign').value==='left'?'0':'auto';figure.style.marginRight=$('extraAlign').value==='right'?'0':'auto'}if(extraImageWidthChanged){figure.style.width=width+'%';figure.style.maxWidth='100%';image.style.width='100%';image.style.height='auto'}let caption=figure.querySelector('figcaption,.se-caption,.se_mediaCaption');const captionText=$('extraCaption').value;if(captionText!==(caption?.textContent||'')){if(captionText.trim()){if(!caption){caption=document.createElement('figcaption');figure.append(caption)}caption.textContent=captionText.trim()}else caption?.remove()}html=figure.outerHTML}
if(extraMode==='html'){extraBusy=true;setBusy(true);$('applyExtra').disabled=true;$('closeExtra').disabled=true;const input={...values(),bodyMarkdown:$('extraText').value};let result;try{result=await api('/posts/'+encodeURIComponent(current.id)+'/preview',{method:'POST',body:JSON.stringify({input})})}finally{extraBusy=false;setBusy(false);$('applyExtra').disabled=false;$('closeExtra').disabled=false}if(typeof result.editorHtml!=='string')throw new Error('HTML을 적용할 수 없습니다. 화면을 새로 연 뒤 다시 시도하세요.');extraTarget=null;closeExtraDialog(false);replaceEditorHtml(result.editorHtml);return}
const originalLinks=extraMode==='card'?new Set($('bodyHtml').querySelectorAll('a')):null;closeExtraDialog(false);if(extraTarget&&['card','image'].includes(extraMode))replaceExtraTarget(html);else{clearMediaSelection();formatCommand('insertHTML',html)}if(originalLinks){for(const card of $('bodyHtml').querySelectorAll('[data-editor-inserted-card]')){card.removeAttribute('contenteditable');card.removeAttribute('data-editor-inserted-card')}for(const link of $('bodyHtml').querySelectorAll('a'))if(!originalLinks.has(link)&&!link.textContent.trim()&&!link.querySelector('img,svg,video,iframe'))link.remove()}}catch(error){$('extraError').textContent=error.message;$('extraLogin').hidden=error.code!=='authentication_required'}};
$('editSelectedMedia').onclick=()=>{if(!selectedMedia)return;openExtra(selectedMedia.kind==='link-card'?'card':'image',selectedMedia.node)};
`;
