export const adminNavigationHtml = `<aside id="adminLinkNotice" class="management-error" role="status" hidden><p id="adminLinkMessage"></p><div class="row"><button id="retryAdminLink" type="button" hidden>연결 다시 시도</button><a id="openAdminLinkTab" target="_blank" rel="noopener noreferrer" hidden>새 탭에서 열기</a><button id="dismissAdminLink" type="button">닫기</button></div></aside>`;

export const adminNavigationScript = String.raw`
let handledAdminHash=null,observedAdminHash=null,adminLinkBusy=false,adminReady=false;
function parseAdminDestination(hash){if(!hash||hash==='#')return null;const params=new URLSearchParams(hash.slice(1)),entries=Array.from(params.entries());if(entries.length!==1)throw requestError('관리 화면 연결 주소가 올바르지 않습니다. 글 목록에서 원하는 항목을 선택해 주세요.','invalid_admin_link');const [key,value]=entries[0];if(key==='view'&&['posts','new','statistics','settings'].includes(value))return {view:value};if(key==='edit'&&(/^\/posts\/[1-9]\d{0,14}$/.test(value)||/^\/pages\/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/.test(value)))return {path:value};throw requestError('편집할 글 주소가 올바르지 않습니다. 글 목록에서 원하는 글을 선택해 주세요.','invalid_admin_link')}
function adminLinkNotice(message,{retry=false,newTab=false}={}){$('adminLinkNotice').hidden=false;$('adminLinkMessage').textContent=message;$('retryAdminLink').hidden=!retry;$('openAdminLinkTab').hidden=!newTab;if(newTab)$('openAdminLinkTab').href='/'+(window.location?.hash||'');else $('openAdminLinkTab').removeAttribute('href');$('adminLinkNotice').scrollIntoView({block:'nearest'})}
function currentAdminPath(){return current?.publicPath||(current?.globalSequence?'/posts/'+current.globalSequence:null)}
async function followAdminDeepLink(){const hash=window.location?.hash||'';if(observedAdminHash!==hash){observedAdminHash=hash;handledAdminHash=null}if(!adminReady||adminLinkBusy||busy||handledAdminHash===hash)return;let destination;try{destination=parseAdminDestination(hash)}catch(error){adminLinkNotice(error.message);handledAdminHash=hash;return}if(!destination){handledAdminHash=hash;return}if(blocked){adminLinkNotice('먼저 로그인 또는 작업본 저장 문제를 해결해 주세요. 연결할 위치는 이 탭에 유지됩니다.',{retry:true,newTab:true});return}
 if(destination.path&&currentAdminPath()===destination.path){handledAdminHash=hash;$('adminLinkNotice').hidden=true;openEditorLocation(true);return}
 if(destination.path&&(dirty||saving||hasManagementChanges())){adminLinkNotice('현재 입력을 유지하기 위해 다른 글로 이동하지 않았습니다. 새 탭에서 해당 글을 열 수 있습니다.',{retry:true,newTab:true});return}
 if(destination.view){handledAdminHash=hash;$('adminLinkNotice').hidden=true;if(destination.view==='statistics'){await $('manageStatistics').onclick();return}if(destination.view==='settings'){await openManagement('settings',$('manageSettings'),true);return}showPostList();if(destination.view==='new'){$('postKind').value='';$('new').focus({preventScroll:true});adminLinkNotice('새 글을 쓰려면 새 글 쓰기 버튼을 누르세요. 아직 초안은 만들지 않았습니다.')}return}
 adminLinkBusy=true;setBusy(true);try{const result=await api('/posts/resolve?path='+encodeURIComponent(destination.path));if(hash!==(window.location?.hash||''))return;const post=result.post;if(!post||post.publicPath!==destination.path)throw requestError('해당 주소의 기존 글을 찾지 못했습니다. 글 목록에서 확인해 주세요.','post_not_found');fill(post);handledAdminHash=hash;$('adminLinkNotice').hidden=true;openEditorLocation()}catch(error){if(hash!==(window.location?.hash||''))return;adminLinkNotice(error.code==='post_not_found'?'해당 주소의 기존 글을 찾지 못했습니다. 새 글은 만들지 않았습니다.':error.message,{retry:error.code!=='post_not_found',newTab:error.code==='authentication_required'})}finally{adminLinkBusy=false;setBusy(false);if(hash!==(window.location?.hash||''))void followAdminDeepLink()}}
$('retryAdminLink').onclick=()=>followAdminDeepLink();$('dismissAdminLink').onclick=()=>{$('adminLinkNotice').hidden=true;handledAdminHash=window.location?.hash||''};
window.addEventListener('hashchange',()=>{void followAdminDeepLink()});
`;
