import { categoryDisplayId, categoryDisplayLabel, categoryEditorChoices } from './category-display.ts';
import { imageDirectToolsHtml, imageDirectOverlayHtml, imageDirectCss, imageDirectScript } from './admin-image-direct.ts';
import { editorHistoryScript } from './admin-editor-history.ts';
import { autoLinkScript } from './admin-autolink.ts';
import { imageLayoutHtml, imageLayoutScript } from './admin-image-layout.ts';
import { adminNavigationHtml, adminNavigationScript } from './admin-navigation.ts';
import { statisticsCss, statisticsDialogHtml, statisticsScript } from './admin-statistics.ts';
import { extrasCss, extrasHtml, extrasScript } from './admin-extras.ts';
import { IMPORTED_PRESENTATION_CSS, ENGINE_DIAGRAM_CSS } from './imported-presentation.ts';
import { mountEngineDiagram } from './engine-diagram-client.js';
import { TAXONOMY } from './taxonomy.ts';
import { managementCss, managementNavigationHtml, managementPaginationHtml, managementDialogsHtml, managementPostInfoHtml, managementScript, publishingDialogsHtml, publishingScript } from './admin-management.ts';
import { formattingCss, formattingScript, formattingToolbarHtml } from './admin-formatting.ts';

function jsonForScript(value: unknown) {
  return JSON.stringify(value).replace(/</gu, '\\u003c');
}

export function adminHtml(identityEmail: string) {
  const categories = TAXONOMY.map(({ id, label, parentId, order }) => ({ id, label, parentId, sortOrder: order }));
  const nativeImagePattern = String.raw`!\[([^\]]*)\]\((\/media\/native\/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}\.(?:avif|gif|jpe?g|png|webp))\)`;
  return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>dwnc.me 글쓰기</title>
<style>
:root{font-family:system-ui,-apple-system,BlinkMacSystemFont,sans-serif;color:#202124;background:#fff;--editor-header-height:72px;--editor-footer-height:88px}
*{box-sizing:border-box}body{margin:0}body:has(dialog[open]){overflow:hidden}[hidden]{display:none!important}
button,input,textarea,select{font:inherit}button{padding:10px 16px;border:1px solid #d9dce1;border-radius:5px;background:#fff;color:#333;cursor:pointer}button:hover{background:#f6f7f8}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:2px solid #1769d2;outline-offset:3px}button:disabled{opacity:.45;cursor:default}button.publish{background:#222;color:#fff;border-color:#222}button.publish:hover{background:#111}.row{display:flex;flex-wrap:wrap;gap:12px;align-items:center}.grow{flex:1;min-width:0}
input,textarea,select{width:100%;padding:10px 12px;border:1px solid #d9dce1;border-radius:4px;background:#fff}label{display:block;margin:0 0 6px;font-size:14px;color:#555}textarea{resize:vertical}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.editor-header{position:fixed;inset:0 0 auto;z-index:30;display:flex;align-items:center;gap:20px;min-height:72px;padding:12px 24px;border-bottom:1px solid #e9e9ec;background:#fff}.brand-strip{display:flex;align-items:center;gap:12px;flex-shrink:0}.brand{font-size:23px;font-weight:700;letter-spacing:-1.2px;color:#111;text-decoration:none}.brand span{font-weight:450;color:#888}.brand-strip button{font-size:13px;padding:7px 9px;white-space:nowrap;border-color:transparent}.account-label{font-size:12px;color:#888;margin-left:auto;overflow-wrap:anywhere}body[data-view="editor"] .account-label{display:none}#editorTools{flex:1;min-width:0}
main{padding:calc(var(--editor-header-height) + 44px) 24px calc(var(--editor-footer-height) + 52px);min-height:100vh}.posts-view{max-width:960px;margin:0 auto}.posts-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:28px}.posts-heading h1{margin:0;font-size:28px;font-weight:650}.posts-intro{color:#787b80;font-size:14px;margin:10px 0 26px}.posts{list-style:none;padding:0;margin:0}.posts li{border-bottom:1px solid #eceef0}.posts button{display:block;width:100%;padding:20px 16px;border:0;border-radius:0;text-align:left;line-height:1.5;overflow-wrap:anywhere;background:#fff}.posts button:hover{background:#fafafa}.posts button[aria-current="true"]{background:#f2f6fb;color:#175da3;box-shadow:inset 3px 0 #175da3}
.editor-view{width:100%;max-width:860px;margin:0 auto}.editor-context{height:0;font-size:0;line-height:0;margin:0;overflow:hidden;scroll-margin-top:calc(var(--editor-header-height) + 28px)}.category-field{width:210px;margin:0 0 20px}.category-field select{border-color:#e0e2e4;color:#5d6066;font-size:14px;padding:9px 12px}.title-input{padding:8px 0 24px;border:0;border-radius:0;border-bottom:1px solid #e5e5e5;font-size:34px;line-height:1.4;font-weight:500;letter-spacing:-.9px;outline-offset:6px}.title-input::placeholder{color:#b8babd;font-weight:400}.body-field{margin-top:32px}.html-editor-shell{position:relative;min-width:0}.html-editor{min-height:48vh;padding:0;border:0;background:#fff;outline:none;overflow-wrap:anywhere}.html-editor:empty:before{content:attr(data-placeholder);color:#a7abb0;pointer-events:none}.html-editor:focus{outline:none}.html-editor:focus-visible{outline:none}.tag-field{margin:34px 0 24px;padding-top:20px;border-top:1px solid #eeeeef}.tag-field input{border:0;padding:8px 0;font-size:15px}.tag-field input::placeholder{color:#9ba0a6}.post-details{margin:26px 0;color:#777;font-size:14px}.post-details summary{cursor:pointer;padding:8px 0}.post-details label{margin-top:12px}.post-details input{font-size:14px}
.editor-footer{position:fixed;inset:auto 0 0;z-index:30;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:28px;align-items:center;min-height:80px;padding:14px 32px;border-top:1px solid #e5e7e9;background:#fff}.editor-footer>button{min-width:100px}.save-state{text-align:center;min-width:0}.save-state p{margin:3px 0;line-height:1.45}.save-state #saveStatus{font-size:13px;color:#555}.save-detail{font-size:11px;color:#91969d}.status{position:fixed;right:24px;bottom:calc(var(--editor-footer-height) + 12px);z-index:35;max-width:min(520px,calc(100vw - 48px));margin:0;padding:0;font-size:13px;color:#59636e;pointer-events:none}.status:not(:empty){padding:10px 14px;border:1px solid #e2e6e9;border-radius:5px;background:#fffffff2;box-shadow:0 2px 10px #0000000a}.save-issue{position:fixed;z-index:45;left:50%;bottom:calc(var(--editor-footer-height) + 14px);transform:translateX(-50%);width:min(760px,calc(100vw - 32px));max-height:45vh;overflow:auto;padding:18px 20px;border:1px solid #d6b682;border-radius:8px;background:#fffaf0;box-shadow:0 6px 24px #0002}.save-issue p{margin:0 0 12px;line-height:1.65;font-size:14px}.save-issue button,.save-issue a{font-size:13px}.save-issue a{color:#175da3}
.upload-panel{position:fixed;z-index:40;top:calc(var(--editor-header-height) + 10px);left:24px;width:min(470px,calc(100vw - 48px));padding:18px;border:1px solid #d9dde2;border-radius:6px;background:#fff;box-shadow:0 5px 22px #0002}.upload-panel p{margin:0 0 12px;font-size:13px;color:#777}.upload-panel input{margin-bottom:12px;font-size:13px}.upload-panel button{font-size:13px}
.html-editor img{max-width:100%;height:auto}
/* Imported player menus have no platform stylesheet or playable source. Keep
   their fixed-height boxes from spilling over the editor's post information.
   CSS-only presentation leaves the saved legacy HTML and captions untouched. */
.html-editor .naver-content :is(._naverVideo,.prismplayer-area):has(video.webplayer-internal-video):not(:has(video[src],source[src],.naver-video-fallback)){display:block;width:100%!important;max-width:100%;height:auto!important;min-height:0;overflow:hidden;margin-block:18px;padding:24px;border:1px solid #e2e2dc;border-radius:7px;background:#fafaf7;text-align:center}
.html-editor .naver-content :is(._naverVideo,.prismplayer-area):has(video.webplayer-internal-video):not(:has(video[src],source[src],.naver-video-fallback))>*{display:none!important}
.html-editor .naver-content :is(._naverVideo,.prismplayer-area):has(video.webplayer-internal-video):not(:has(video[src],source[src],.naver-video-fallback))::before{content:"이전 블로그 동영상은 편집기에서 재생할 수 없습니다.";display:block;color:#666;font:14px/1.7 system-ui,sans-serif}
.html-editor figure.imageblock,.html-editor .se_component.se_image,.html-editor .se-component.se-image{display:block;margin:18px 0;padding:8px;border:1px solid #e2e2dc;border-radius:7px}
.html-editor figure[data-ke-type="opengraph"],.html-editor .se_component.se_oglink,.html-editor .se-component.se-oglink{display:block;margin:18px 0;border:1px solid #c8c8c0;border-radius:8px;background:#fafaf7;overflow:hidden}
.html-editor figure[data-ke-type="opengraph"]>a{display:grid;grid-template-columns:minmax(120px,32%) 1fr;color:inherit;text-decoration:none}
.html-editor .se-oglink-info{display:block;color:inherit;text-decoration:none}.html-editor .se-oglink-info:has(.se-oglink-thumbnail){display:grid;grid-template-columns:minmax(120px,32%) 1fr}
.html-editor .og-image,.html-editor .se-oglink-thumbnail{min-height:110px;background:#e8e8e2}
.html-editor .og-image img,.html-editor .se-oglink-thumbnail img{display:block;width:100%;height:100%;min-height:110px;object-fit:cover}
.html-editor .og-image__label{display:grid;min-height:110px;place-items:center;color:#666;font-size:.9rem}
.html-editor .og-text,.html-editor .se-oglink-info-container{min-width:0;padding:14px}
.html-editor .og-title,.html-editor .se-oglink-title{display:-webkit-box;margin:0 0 6px;overflow:hidden;font-weight:750;line-height:1.35;-webkit-box-orient:vertical;-webkit-line-clamp:2}
.html-editor .og-desc,.html-editor .se-oglink-summary{display:-webkit-box;margin:0 0 9px;overflow:hidden;color:#555;font-size:.92rem;line-height:1.45;-webkit-box-orient:vertical;-webkit-line-clamp:3}
.html-editor .og-host,.html-editor .se-oglink-url{margin:0;color:#777;font-size:.82rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.media-selection-outline{position:absolute;z-index:2;border:3px solid #1264d1;border-radius:7px;box-shadow:0 0 0 3px rgba(18,100,209,.18);pointer-events:none}
.image-tools{position:fixed;z-index:20;display:flex;align-items:center;justify-content:space-between;gap:12px;max-width:calc(100vw - 24px);padding:10px 12px;border:1px solid #9bb8df;border-radius:7px;background:#eef5ff;box-shadow:0 4px 18px rgba(0,0,0,.18)}
.image-tools{flex-wrap:wrap}.image-tools button{background:#9b1c1c}.image-tools #setSelectedCover{background:#1769d2}.image-tools__label{font-weight:650;color:#123c73}

.image-tools{z-index:40}.image-tools button{color:#fff}.image-tools__label{font-size:13px}.markdown-media[hidden]{display:none}
${formattingCss}
${managementCss}
${statisticsCss}
${extrasCss}
${imageDirectCss}

.preview-dialog{width:100vw;height:100dvh;max-width:none;max-height:none;margin:0;padding:0;inset:0;border:0;background:#f3f4f6;color:#222}.preview-dialog[open]{display:flex;flex-direction:column}.preview-dialog::backdrop{background:#fff}.preview-toolbar{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap;padding:16px 28px;border-bottom:1px solid #e0e2e5;background:#fff;flex-shrink:0}.preview-toolbar h2{font-size:16px;font-weight:550;margin:0}.preview-toolbar p{font-size:12px;color:#888;margin:5px 0 0}.preview-toolbar button{font-size:13px;padding:8px 14px}.preview-toolbar button[aria-pressed="true"]{background:#222;color:#fff;border-color:#222}.preview-scroll{flex:1;overflow:auto;padding:44px 24px 70px;min-height:0}.preview-viewport{width:min(100%,960px);margin:0 auto;padding:54px;background:#fff;min-height:70vh;box-shadow:0 2px 18px #00000008;overflow-wrap:anywhere}.preview-viewport[data-size="mobile"]{width:min(100%,390px);padding:26px 20px}.preview-title{font-size:32px;line-height:1.45;margin:0 0 36px;letter-spacing:-.6px;overflow-wrap:anywhere}.preview-viewport[data-size="mobile"] .preview-title{font-size:25px}.preview{font-size:16px;line-height:1.8;overflow-wrap:anywhere}.preview img,.preview video,.preview iframe{max-width:100%;height:auto}.preview table{border-collapse:collapse;max-width:100%}.preview :is(td,th){border:1px solid #ccc;padding:8px}.preview blockquote{padding:.3em 1em;border-left:3px solid #aaa;margin:1em 0}.preview pre{overflow:auto}.preview a{color:#175da3}
@media(max-width:760px){.editor-header{flex-wrap:wrap;gap:8px;padding:10px 16px;min-height:60px}.brand-strip{width:100%;gap:12px}.brand{font-size:21px}.brand-strip #attachPhoto{margin-left:auto}#editorTools{flex-basis:100%;max-width:100%}.account-label{display:none}main{padding:calc(var(--editor-header-height) + 30px) 22px calc(var(--editor-footer-height) + 36px)}.title-input{font-size:28px;padding-bottom:20px}.body-field{margin-top:25px}.editor-footer{gap:14px;padding:12px 20px}.editor-footer>button{min-width:88px;padding:10px 12px}.save-state #saveStatus{font-size:12px}.save-detail{font-size:10px}.preview-toolbar{padding:14px 18px}.preview-scroll{padding:24px 12px 40px}.preview-viewport{padding:32px 24px}.preview-title{font-size:28px}.html-editor figure[data-ke-type="opengraph"]>a,.html-editor .se-oglink-info:has(.se-oglink-thumbnail){display:block}}
@media(max-width:480px){main{padding-inline:20px}.title-input{font-size:26px}.category-field{width:180px}.editor-footer{grid-template-columns:1fr 1fr;gap:9px 14px;padding:10px 16px}.save-state{grid-column:1/-1;grid-row:1}.editor-footer #preview{grid-row:2;justify-self:start}.editor-footer #publish{grid-row:2;justify-self:end}.save-detail{font-size:10px}.status{right:16px;max-width:calc(100vw - 32px)}.posts-heading{align-items:flex-start;flex-wrap:wrap}.posts-heading h1{font-size:25px}.posts button{padding:17px 10px}.preview-toolbar{gap:12px}.preview-toolbar h2{font-size:15px}.preview-toolbar .row{gap:6px}.preview-toolbar button{padding:7px 11px}.preview-scroll{padding:14px 10px 28px}.preview-viewport{padding:25px 20px}.preview-title{font-size:25px}}
${IMPORTED_PRESENTATION_CSS}
${ENGINE_DIAGRAM_CSS}
#previewBox.prose{width:100%;margin:0;padding:0}
</style></head><body>
<header id="editorHeader" class="editor-header"><div class="brand-strip"><a class="brand" href="https://dwnc.me/" target="_blank" rel="noopener noreferrer" aria-label="dwnc.me 블로그 홈 (새 탭)">dwnc<span>.me</span></a><button id="showPosts" type="button" hidden>글 목록</button><button id="attachPhoto" type="button" hidden>사진 첨부</button></div><div id="editorTools" hidden>${formattingToolbarHtml}</div><span class="account-label">${identityEmail.replace(/[&<>"']/gu, '')}</span></header>
<main>${adminNavigationHtml}<section id="postsPanel" class="posts-view" aria-label="글 목록"><div class="posts-heading"><h1>글 목록</h1><div class="row"><button id="resumeEditing" type="button" hidden>작성 중인 글로 돌아가기</button><button id="new" class="publish" type="button">새 글 쓰기</button></div></div><p class="posts-intro">글을 선택해서 이어 쓰거나 새 글을 작성하세요.</p>${managementNavigationHtml}<ul id="posts" class="posts"></ul>${managementPaginationHtml}</section>
<section id="editorView" class="editor-view" hidden><h1 id="heading" class="editor-context">글을 선택하세요</h1><form id="editor" hidden><div class="category-field"><label for="category" class="sr-only">카테고리</label><select id="category" aria-label="카테고리"></select></div><label for="title" class="sr-only">제목</label><input id="title" class="title-input" maxlength="180" placeholder="제목을 입력하세요"><div class="body-field"><label id="bodyLabel" for="bodyHtml" class="sr-only">본문</label><textarea id="body" hidden></textarea><div id="markdownMedia" class="markdown-media" aria-label="본문 이미지" hidden></div><div id="bodyHtmlShell" class="html-editor-shell"><div id="bodyHtml" class="html-editor" contenteditable="true" role="textbox" aria-label="본문" aria-multiline="true" data-placeholder="여기에 내용을 입력하세요."></div><div id="mediaSelectionOutline" class="media-selection-outline" hidden></div></div></div><div class="tag-field"><label for="tags" class="sr-only">태그 (쉼표 구분)</label><input id="tags" placeholder="#태그를 입력하세요 (쉼표로 구분)"><div id="tagSuggestions" class="tag-suggestions" aria-label="태그 추천"></div></div><details class="post-details"><summary>글 정보</summary>${managementPostInfoHtml}<label for="description">요약</label><input id="description" maxlength="320" placeholder="목록에 보여 줄 짧은 소개를 입력하세요"></details></form></section></main>
<div id="uploadPanel" class="upload-panel" hidden><p>사진을 여러 장 선택해 본문의 커서 위치에 순서대로 넣을 수 있습니다.</p><input id="image" type="file" multiple aria-label="첨부할 사진" accept="image/avif,image/gif,image/jpeg,image/png,image/webp"><div class="row"><button id="upload" type="button">사진 올리고 본문에 넣기</button><button id="closeUpload" type="button">닫기</button></div></div>
<div id="imageTools" class="image-tools" role="toolbar" aria-label="선택한 본문 이미지" hidden><span id="imageSelectionLabel" class="image-tools__label"></span>${imageDirectToolsHtml}<button id="setSelectedCover" type="button" hidden>이 사진을 대표이미지로 지정</button><button id="selectedImageLayout" type="button">배치 더보기</button><button id="editSelectedMedia" type="button">편집</button><button id="deleteImage" type="button">선택 항목 삭제</button></div>
<footer id="editorFooter" class="editor-footer" hidden><button id="preview" type="button" disabled>미리보기</button><div class="save-state" aria-live="polite"><p id="saveStatus">글을 선택하면 작업본 저장 상태가 표시됩니다.</p><p id="lastSaved" class="save-detail"></p></div><button id="publish" class="publish" type="button" disabled>공개 반영</button></footer>
<div id="saveIssue" class="save-issue" role="alert" hidden><p id="issueMessage"></p><div class="row"><button id="retrySave" type="button">다시 시도</button><a id="loginLink" href="/" target="_blank" rel="noopener">새 탭에서 로그인</a><button id="resumeLogin" type="button">로그인 완료 · 이어서 저장</button><button id="loadLatest" type="button" hidden>현재 입력 대신 최신 작업본 불러오기</button><button id="keepLocal" type="button" hidden>현재 작성본 유지</button></div></div><p id="status" class="status" aria-live="polite"></p>
${imageDirectOverlayHtml}
${imageLayoutHtml}
<dialog id="previewDialog" class="preview-dialog" aria-labelledby="previewHeading"><div class="preview-toolbar"><div><h2 id="previewHeading">미리보기</h2><p>현재 작업본입니다. 공개 반영 전에는 방문자에게 보이지 않습니다.</p></div><div class="row"><button id="previewDesktop" type="button" aria-pressed="true">PC</button><button id="previewMobile" type="button" aria-pressed="false">모바일</button><button id="previewClose" type="button" aria-label="미리보기 닫기">닫기 ✕</button></div></div><div class="preview-scroll"><article id="previewViewport" class="preview-viewport" data-size="desktop"><h1 id="previewTitle" class="preview-title"></h1><div id="previewBox" class="preview prose" hidden></div></article></div></dialog>
${managementDialogsHtml}
${statisticsDialogHtml}
${publishingDialogsHtml}
${extrasHtml}
<script>
const categoryDisplayId=${categoryDisplayId.toString()};
const categoryDisplayLabel=${categoryDisplayLabel.toString()};
const categoryEditorChoices=${categoryEditorChoices.toString()};
let categories=${jsonForScript(categories)};let current=null,timer=null,saving=null,dirty=false,change=0,selectedMedia=null,busy=false,blocked=null,retryAction=null,lastSavedAt=null,view='list',editorScrollY=0,listScrollY=0,uploadRange=null,noticeTimer=null,uploadQueue=[];
const $=id=>document.getElementById(id), status=m=>{clearTimeout(noticeTimer);$('status').textContent=m;if(m)noticeTimer=setTimeout(()=>{$('status').textContent=''},6000)};
for(const c of categoryEditorChoices(categories)){const o=document.createElement('option');o.value=c.id;o.textContent=c.label;$('category').append(o)}
function requestError(message,code){const error=new Error(message);error.code=code;return error}
async function api(path,options={}){
  const controller=new AbortController(),deadline=setTimeout(()=>controller.abort(),path.endsWith('/media')?120000:30000);
  try{
  let r;try{r=await fetch('/api'+path,{credentials:'same-origin',redirect:'manual',cache:'no-store',...options,signal:controller.signal,headers:{'content-type':'application/json',...(options.headers||{})}})}catch{throw requestError(controller.signal.aborted?'응답이 늦어 저장 성공을 확인하지 못했습니다. 작성 내용은 유지됩니다. 다시 시도하세요.':'연결하지 못했습니다. 인터넷 연결을 확인하고 다시 시도하세요. 로그인이 만료됐다면 새 탭에서 로그인할 수 있습니다.','connection_failed')}
  if(r.type==='opaqueredirect'||r.status===401||r.status===403||r.status>=300&&r.status<400)throw requestError('로그인이 필요합니다. 이 탭을 그대로 두고 새 탭에서 로그인한 뒤 돌아오세요.','authentication_required');
  const contentType=r.headers.get('content-type')||'';if(!contentType.includes('application/json'))throw requestError(contentType.includes('text/html')?'로그인이 필요합니다. 이 탭을 그대로 두고 새 탭에서 로그인한 뒤 돌아오세요.':'서버 응답을 확인하지 못했습니다. 다시 시도하세요.',contentType.includes('text/html')?'authentication_required':'invalid_response');
  let j;try{j=await r.json()}catch{throw requestError('서버 응답을 확인하지 못했습니다. 다시 시도하세요.','invalid_response')}
  if(!r.ok)throw requestError(j.error||'요청을 완료하지 못했습니다.',j.code||(r.status===409?'revision_conflict':'request_failed'));return j;
  }finally{clearTimeout(deadline)}
}
function renderSaveState(){
  if(!current)return;
  const publicState=publicationDescription(current);
  let message=saving?'작업본 저장 중…':dirty?'작업본에 아직 저장하지 못한 변경이 있습니다.':'작업본 저장됨';
  if(blocked==='conflict')message='다른 곳에서 수정됨 · 현재 작성 내용은 이 화면에 유지됩니다.';
  else if(blocked==='review')message='현재 작성본 유지 중 · 아래 저장 버튼을 누를 때까지 자동저장을 멈춥니다.';
  else if(blocked==='authentication_required')message='로그인 필요 · 현재 작성 내용은 이 화면에 유지됩니다.';
  else if(blocked)message='요청 실패 · 현재 작성 내용은 이 화면에 유지됩니다.';
  else if(!dirty&&!saving&&current.status==='published')message+=current.revision===current.publishedRevision?' · 공개 내용과 같습니다.':' · 공개 반영을 기다리는 변경이 있습니다.';
  updatePublicationSummary();$('saveStatus').textContent=message;$('lastSaved').textContent=(lastSavedAt?'마지막 저장 성공: '+new Date(lastSavedAt).toLocaleString('ko-KR',{timeZone:siteTimezone}):'아직 저장 성공을 확인하지 못했습니다.')+' · '+publicState;
}
function setBusy(value){busy=value;for(const id of ['new','preview','publish','upload','retrySave','resumeLogin','loadLatest','keepLocal','showPosts','resumeEditing','attachPhoto','manageCategories','manageSettings','manageStatistics','manageTemplates','chooseCover','insertTemplate','publicationOptions','deleteEmptyDraft'])$(id).disabled=value||(['preview','publish','upload'].includes(id)&&!current);for(const node of $('posts').querySelectorAll('button'))node.disabled=value;for(const id of ['postSearch','postCategory','postStatus','postKind'])$(id).disabled=value;$('postPrevious').disabled=value||postPage<=1;$('postNext').disabled=value||postPage>=postPages;for(const id of ['title','description','category','tags','body','image'])$(id).disabled=value;$('bodyHtml').contentEditable=value?'false':'true';$('deleteImage').disabled=value;$('editSelectedMedia').disabled=value;$('setSelectedCover').disabled=value;setFormattingBusy(value);updatePublicationSummary()}
function clearIssue(){blocked=null;retryAction=null;$('saveIssue').hidden=true;renderSaveState()}
function showIssue(error,retry){
  clearTimeout(timer);blocked=error.code==='revision_conflict'?'conflict':error.code||'request_failed';retryAction=retry;$('saveIssue').hidden=false;
  $('issueMessage').textContent=blocked==='conflict'?'다른 탭이나 세션에서 먼저 저장했습니다. 현재 입력 대신 최신 작업본을 불러오거나, 현재 작성본을 유지한 뒤 직접 저장할 수 있습니다.':error.message;
  const conflict=blocked==='conflict';$('loadLatest').hidden=!conflict;$('keepLocal').hidden=!conflict;$('retrySave').hidden=conflict||blocked==='authentication_required';$('retrySave').textContent='다시 시도';$('loginLink').hidden=conflict;$('resumeLogin').hidden=conflict;renderSaveState();
}
async function action(work){if(busy)return;setBusy(true);try{await work()}catch(error){showIssue(error,work)}finally{setBusy(false);renderSaveState()}}
function values(){return{kind:$('contentKind').value||current?.kind||'post',title:$('title').value,description:$('description').value,bodyFormat:'html',bodyMarkdown:$('bodyHtml').innerHTML,categoryId:$('category').value,tags:$('tags').value.split(',').map(v=>v.trim()).filter(Boolean),coverMediaId:current?.coverMediaId||null,coverPath:current?.coverPath??null,coverAlt:current?.coverAlt||''}}
function clearMediaSelection(){if(selectedMedia?.kind==='markdown-image')selectedMedia.node.setAttribute('aria-pressed','false');selectedMedia=null;$('setSelectedCover').hidden=true;$('mediaSelectionOutline').hidden=true;$('imageTools').hidden=true}
function positionImageTools(node){const tools=$('imageTools'),box=node.getBoundingClientRect(),tool=tools.getBoundingClientRect(),gap=8,margin=12,topLimit=Math.max(margin,$('editorHeader').getBoundingClientRect().bottom+gap),bottomLimit=$('editorFooter').hidden?window.innerHeight-margin:$('editorFooter').getBoundingClientRect().top-margin;let top=box.top-tool.height-gap;if(top<topLimit)top=box.bottom+gap;top=Math.max(topLimit,Math.min(top,bottomLimit-tool.height));let left=box.right-tool.width;left=Math.max(margin,Math.min(left,window.innerWidth-tool.width-margin));tools.style.top=top+'px';tools.style.left=left+'px'}
function positionMediaSelection(){if(!selectedMedia)return;if(selectedMedia.kind==='markdown-image'){if(!$('markdownMedia').contains(selectedMedia.node)){clearMediaSelection();return}$('mediaSelectionOutline').hidden=true;positionImageTools(selectedMedia.node);return}if(!$('bodyHtml').contains(selectedMedia.node)){clearMediaSelection();return}const shell=$('bodyHtmlShell'),box=selectedMedia.node.getBoundingClientRect(),host=shell.getBoundingClientRect(),outline=$('mediaSelectionOutline');outline.style.left=box.left-host.left+shell.scrollLeft+'px';outline.style.top=box.top-host.top+shell.scrollTop+'px';outline.style.width=box.width+'px';outline.style.height=box.height+'px';outline.hidden=false;positionImageTools(selectedMedia.node)}
function mediaTarget(node){const card=node.closest('figure[data-ke-type="opengraph"],.se_component.se_oglink,.se-component.se-oglink');if(card)return{node:card,kind:'link-card'};const block=node.closest('figure.imageblock,.se_component.se_image,.se-component.se-image');return{node:block||node,kind:'image'}}
function selectMedia(node){const selection=mediaTarget(node),label=selection.kind==='link-card'?'링크 미리보기 카드':'본문 이미지';selectedMedia=selection;selectedMedia.image=selection.kind==='image'&&node.tagName==='IMG'?node:null;$('setSelectedCover').hidden=!selectedMedia.image;$('bodyHtml').focus({preventScroll:true});$('imageSelectionLabel').textContent=label+'가 선택되었습니다.';$('deleteImage').textContent=selection.kind==='link-card'?'링크 카드 삭제':'이미지 삭제';$('imageTools').hidden=false;updateDirectPhotoTools();positionMediaSelection();status(label+' 선택됨 · Delete 또는 Backspace로 삭제할 수 있습니다.')}
function markdownImageRanges(value){const images=[],pattern=new RegExp(${jsonForScript(nativeImagePattern)},'g'),fence=String.fromCharCode(96).repeat(3);let fenced=false,offset=0;for(const line of value.split(String.fromCharCode(10))){if(line.trim().startsWith(fence))fenced=!fenced;else if(!fenced){pattern.lastIndex=0;for(const match of line.matchAll(pattern))images.push({alt:match[1]||'본문 이미지',path:match[2],start:offset+match.index,end:offset+match.index+match[0].length})}offset+=line.length+1}return images}
function selectMarkdownMedia(node,image){clearMediaSelection();selectedMedia={node,kind:'markdown-image',start:image.start,end:image.end};node.setAttribute('aria-pressed','true');node.focus({preventScroll:true});$('imageSelectionLabel').textContent='본문 이미지가 선택되었습니다.';$('deleteImage').textContent='이미지 삭제';$('imageTools').hidden=false;positionMediaSelection();status('본문 이미지 선택됨 · Delete 또는 Backspace로 삭제할 수 있습니다.')}
function renderMarkdownMedia(){const container=$('markdownMedia'),images=current?.bodyFormat==='html'?[]:markdownImageRanges($('body').value);container.replaceChildren();container.hidden=!images.length;for(const image of images){const button=document.createElement('button'),preview=document.createElement('img'),label=document.createElement('span');button.type='button';button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',(image.alt||'본문 이미지')+' 선택');preview.src=image.path;preview.alt=image.alt;preview.loading='lazy';label.textContent=image.alt||'본문 이미지';button.append(preview,label);button.onclick=event=>{event.preventDefault();selectMarkdownMedia(button,image)};container.append(button)}}
function placeCaret(parent,next){$('bodyHtml').focus();const range=document.createRange();if(next&&$('bodyHtml').contains(next))range.setStartBefore(next);else if(parent&&$('bodyHtml').contains(parent))range.setStart(parent,parent.childNodes.length);else range.selectNodeContents($('bodyHtml'));range.collapse(true);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range)}
function deleteSelectedMedia(){if(busy||!selectedMedia)return false;captureEditorBefore();editorTyping=null;if(selectedMedia.kind==='markdown-image'){const start=selectedMedia.start,end=selectedMedia.end;clearMediaSelection();$('body').setRangeText('',start,end,'end');$('body').focus();schedule();status('이미지를 삭제했습니다. 저장 대기 중입니다.');return true}if(!$('bodyHtml').contains(selectedMedia.node))return false;const target=selectedMedia.node,parent=target.parentNode,next=target.nextSibling,kind=selectedMedia.kind;clearMediaSelection();target.remove();placeCaret(parent,next);schedule();status(kind==='link-card'?'링크 카드를 삭제했습니다. 저장 대기 중입니다.':'이미지를 삭제했습니다. 저장 대기 중입니다.');return true}
function fill(p){clearTimeout(timer);clearMediaSelection();resetFormatting();uploadRange=null;uploadQueue=[];$('uploadPanel').hidden=true;dirty=false;change=0;current=p;$('contentKind').value=p.kind||'post';lastSavedAt=p.updatedAt;clearIssue();$('editor').hidden=false;$('heading').textContent=p.title||'제목 없는 작업본';$('title').value=p.title;$('description').value=p.description;$('body').hidden=true;$('bodyHtmlShell').hidden=false;$('bodyLabel').htmlFor='bodyHtml';$('bodyLabel').textContent='본문';$('body').value='';$('bodyHtml').innerHTML=p.bodyFormat==='html'?p.bodyMarkdown:p.bodyHtml;$('category').replaceChildren();for(const c of categoryEditorChoices(categories,p.categoryId)){const option=document.createElement('option');option.value=c.id;option.textContent=c.label;$('category').append(option)}if(!categories.some(c=>c.id===p.categoryId)){const option=document.createElement('option');option.value=p.categoryId;option.textContent=p.categoryLabel+' (원래 분류)';option.dataset.importedCategory='true';$('category').append(option)}$('category').value=p.categoryId;$('tags').value=p.tags.join(', ');$('image').value='';$('markdownMedia').replaceChildren();$('markdownMedia').hidden=true;$('previewBox').hidden=true;setBusy(busy);status('입력은 작업본에만 자동저장됩니다. 공개 반영을 눌러야 방문자에게 보입니다.');renderSaveState();updateCoverSummary();setView('editor');resetEditorHistory()}
async function list(){const result=await api('/posts'+postListQuery()),{posts}=result;updatePostPagination(result);const ul=$('posts');ul.replaceChildren();for(const p of posts){const li=document.createElement('li'),b=document.createElement('button'),number=p.globalSequence?'#'+p.globalSequence+' ':'';b.textContent=number+postStateLabel(p)+' '+(p.title||'제목 없음');const meta=document.createElement('span');meta.className='post-summary';meta.textContent=[categoryDisplayLabel(p.categoryId,p.categoryLabel),p.updatedAt?new Date(p.updatedAt).toLocaleDateString('ko-KR',{timeZone:siteTimezone}):'',p.status==='published'&&p.hasUnpublishedChanges?'공개하지 않은 변경':''].filter(Boolean).join(' · ');b.append(meta);b.dataset.postId=p.id;b.disabled=busy;b.setAttribute('aria-current',String(current?.id===p.id));b.onclick=async()=>{if(busy)return;if(current?.id===p.id){openEditorLocation(true);return}let opened=false;await action(async()=>{if(!await flush())return;listScrollY=window.scrollY;fill((await api('/posts/'+encodeURIComponent(p.id))).post);opened=true});if(opened)openEditorLocation()};li.append(b);ul.append(li)}}
function markSelectedPost(){for(const button of $('posts').querySelectorAll('button'))button.setAttribute('aria-current',String(button.dataset.postId===current?.id))}
function setView(next){if(view==='list'&&next==='editor')listScrollY=window.scrollY;view=next;document.body.dataset.view=next;$('postsPanel').hidden=next!=='list';$('editorView').hidden=next!=='editor';$('editorFooter').hidden=next!=='editor';$('editorTools').hidden=next!=='editor';$('showPosts').hidden=next!=='editor';$('attachPhoto').hidden=next!=='editor';$('resumeEditing').hidden=!current;positionFormatToolbar()}
function openEditorLocation(resume=false){setView('editor');markSelectedPost();if(resume){window.scrollTo({top:editorScrollY});$('bodyHtml').focus({preventScroll:true})}else{$('heading').scrollIntoView({block:'start'});$('title').focus({preventScroll:true})}}
function showPostList(){if(busy)return;captureFormatRange();editorScrollY=window.scrollY;clearMediaSelection();closeFormatPanels();$('uploadPanel').hidden=true;setView('list');status('');window.scrollTo({top:listScrollY});const selected=$('posts').querySelector('[aria-current="true"]');if(selected)selected.focus({preventScroll:true});else $('new').focus({preventScroll:true})}
function openPreview(html,title){clearMediaSelection();closeFormatPanels();$('uploadPanel').hidden=true;$('previewTitle').textContent=title||'제목 없는 글';$('previewBox').innerHTML=html;const engine=$('previewBox').querySelector('[data-engine-diagram]');if(engine)mountEngineDiagram(engine);$('previewBox').hidden=false;setPreviewSize('desktop');$('previewDialog').showModal();$('previewClose').focus()}
function setPreviewSize(size){$('previewViewport').dataset.size=size;$('previewDesktop').setAttribute('aria-pressed',String(size==='desktop'));$('previewMobile').setAttribute('aria-pressed',String(size==='mobile'))}
function closePreview(){if($('previewDialog').open)$('previewDialog').close()}

async function refreshList(){try{await list()}catch(error){showIssue(error,list)}}
function updateListTitle(post){for(const button of $('posts').querySelectorAll('button')){if(button.dataset.postId===post.id){button.textContent=(post.globalSequence?'#'+post.globalSequence+' ':'')+postStateLabel(post)+' '+(post.title||'제목 없음');const meta=document.createElement('span');meta.className='post-summary';meta.textContent=[categoryDisplayLabel(post.categoryId,post.categoryLabel),post.updatedAt?new Date(post.updatedAt).toLocaleDateString('ko-KR',{timeZone:siteTimezone}):'',post.publishedRevision!==null&&post.publishedRevision!==post.revision?'공개하지 않은 변경':''].filter(Boolean).join(' · ');button.append(meta)}}}
async function flush(){
  clearTimeout(timer);if(blocked)return false;
  while(current&&(dirty||saving)){
    if(saving){if(!await saving)return false;continue}
    const postId=current.id,expected=current.revision,snapshot=values(),savedChange=change;
    saving=(async()=>{try{
      const post=(await api('/posts/'+encodeURIComponent(postId),{method:'PUT',body:JSON.stringify({expectedRevision:expected,input:snapshot})})).post;
      if(current?.id!==postId)return false;
      current=post;lastSavedAt=post.updatedAt;dirty=change!==savedChange;$('heading').textContent=post.title||'제목 없는 작업본';updateListTitle(post);return true;
    }catch(error){dirty=true;showIssue(error,async()=>{await flush()});return false}})();
    renderSaveState();const ok=await saving;saving=null;renderSaveState();if(!ok)return false;
  }
  return true;
}
function schedule(allowBusy=false){if(!current||(busy&&allowBusy!==true))return;rememberEditorChange();dirty=true;change+=1;renderSaveState();clearTimeout(timer);if(!blocked)timer=setTimeout(()=>{void flush()},800)}
for(const id of ['title','description','category','tags'])$(id).addEventListener('input',schedule);
$('body').addEventListener('input',()=>{clearMediaSelection();schedule()});
$('bodyHtml').addEventListener('input',()=>{schedule();positionMediaSelection()});
$('bodyHtml').addEventListener('click',event=>{const element=event.target instanceof Element?event.target:null;if(!element){clearMediaSelection();return}const image=element.closest('img'),card=element.closest('figure[data-ke-type="opengraph"],.se_component.se_oglink,.se-component.se-oglink'),link=element.closest('a');if(link)event.preventDefault();if(card&&$('bodyHtml').contains(card)){event.preventDefault();selectMedia(card.querySelector('img')||card);return}if(image&&$('bodyHtml').contains(image)){event.preventDefault();selectMedia(image);return}clearMediaSelection()});
$('bodyHtml').addEventListener('keydown',event=>{if(selectedMedia&&(event.key==='Delete'||event.key==='Backspace')){event.preventDefault();deleteSelectedMedia()}else if(event.key==='Escape'&&selectedMedia){event.preventDefault();clearMediaSelection()}else if(selectedMedia)clearMediaSelection()});
$('bodyHtml').addEventListener('scroll',positionMediaSelection);
window.addEventListener('resize',positionMediaSelection);
window.addEventListener('scroll',positionMediaSelection,true);
document.addEventListener('click',event=>{const element=event.target instanceof Element?event.target:null;if(!element||(!$('bodyHtml').contains(element)&&!$('markdownMedia').contains(element)&&!$('imageTools').contains(element)&&!$('formatToolbar').contains(element)&&!$('linkPanel').contains(element)&&!$('tablePanel').contains(element)))clearMediaSelection()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&selectedMedia){event.preventDefault();clearMediaSelection()}else if(selectedMedia?.kind==='markdown-image'&&(event.key==='Delete'||event.key==='Backspace')){event.preventDefault();deleteSelectedMedia()}});
$('deleteImage').onclick=()=>deleteSelectedMedia();
$('editor').addEventListener('submit',event=>event.preventDefault());
$('new').onclick=async()=>{let opened=false;await action(async()=>{if(!await flush())return;fill((await api('/posts',{method:'POST',body:JSON.stringify({kind:$('postKind').value||'post'})})).post);opened=true;await refreshList()});if(opened)openEditorLocation()};
$('showPosts').onclick=showPostList;
$('resumeEditing').onclick=()=>{if(current&&!busy)openEditorLocation(true)};
$('preview').onclick=()=>action(async()=>{if(!current||!await flush())return;const snapshot=values();const {html}=await api('/posts/'+encodeURIComponent(current.id)+'/preview',{method:'POST',body:JSON.stringify({input:snapshot})});openPreview(html,snapshot.title)});
$('previewDesktop').onclick=()=>setPreviewSize('desktop');$('previewMobile').onclick=()=>setPreviewSize('mobile');$('previewClose').onclick=closePreview;
$('previewDialog').addEventListener('cancel',event=>{event.preventDefault();closePreview()});
$('previewDialog').addEventListener('close',()=>{$('previewBox').hidden=true;$('preview').focus({preventScroll:true})});
$('attachPhoto').addEventListener('mousedown',event=>event.preventDefault());
$('attachPhoto').onclick=()=>{if(!current||busy)return;captureFormatRange();if(selectedMedia&&$('bodyHtml').contains(selectedMedia.node)){uploadRange=document.createRange();uploadRange.setStartAfter(selectedMedia.node);uploadRange.collapse(true)}else uploadRange=formatRange?.cloneRange()||null;clearMediaSelection();closeFormatPanels();$('uploadPanel').hidden=false;$('image').focus()};
$('closeUpload').onclick=()=>{$('uploadPanel').hidden=true;$('attachPhoto').focus({preventScroll:true})};
$('uploadPanel').addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();$('closeUpload').click()}});

$('publish').onclick=()=>action(async()=>{if(!current||!await flush())return;status('저장한 최신 작업본을 반영하는 중…');const post=(await api('/posts/'+encodeURIComponent(current.id)+'/publish',{method:'POST',body:JSON.stringify({expectedRevision:current.revision,visibility:current.visibility==='scheduled'&&new Date(current.scheduledAt)<=new Date()?'public':current.visibility||'public',scheduledAt:current.scheduledAt})})).post;current=post;lastSavedAt=post.updatedAt;dirty=false;updateListTitle(post);updateCoverSummary();renderSaveState();status('반영 완료 · '+publicationDescription(post));await refreshList()});
$('image').addEventListener('change',()=>{uploadQueue=Array.from($('image').files||[])});
function clipboardImages(data){const files=Array.from(data?.files||[]).filter(file=>file.type.startsWith('image/'));if(files.length)return files;return Array.from(data?.items||[]).filter(item=>item.kind==='file'&&item.type.startsWith('image/')).map(item=>item.getAsFile()).filter(Boolean)}
function pasteImages(files,text=''){if(!current||busy)return;if(uploadQueue.length){status('먼저 올리던 사진을 다시 시도하거나 마무리한 뒤 붙여넣어 주세요. 이전 사진과 작성 내용은 유지했습니다.');return}if(files.some(file=>!['image/avif','image/gif','image/jpeg','image/png','image/webp'].includes(file.type)||file.size<1||file.size>25*1024*1024)){status('사진은 AVIF·GIF·JPEG·PNG·WebP 형식으로 한 장당 25MB 이하만 붙여넣을 수 있습니다. 본문은 그대로 유지했습니다.');return}uploadRange=bodyRange()?.cloneRange()||null;if(text){const node=document.createTextNode(text);if(uploadRange){uploadRange.deleteContents();uploadRange.insertNode(node);uploadRange.setStartAfter(node);uploadRange.collapse(true)}else{$('bodyHtml').append(node);uploadRange=document.createRange();uploadRange.setStartAfter(node);uploadRange.collapse(true)}schedule()}uploadQueue=files;clearMediaSelection();closeFormatPanels();$('uploadPanel').hidden=false;return action(uploadImage)}
async function uploadImage(){
  if(!uploadQueue.length)uploadQueue=Array.from($('image').files||[]);if(!uploadQueue.length||!current){status('사진을 선택하세요.');return}if(!await flush()){retryAction=uploadImage;return}
  const postId=current.id;while(uploadQueue.length){const f=uploadQueue[0];status('사진 '+uploadQueue.length+'장 올리는 중…');const bytes=new Uint8Array(await f.arrayBuffer()),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');
  const j=await api('/posts/'+encodeURIComponent(postId)+'/media',{method:'POST',headers:{'content-type':f.type,'x-dwnc-file-size':String(f.size),'x-dwnc-file-sha256':hash,'x-dwnc-file-name':encodeURIComponent(f.name)},body:bytes});
  if(current?.id!==postId)return;const name=(f.name||'이미지').replace(/[<>&"']/g,'');
  captureEditorBefore();editorTyping=null;const figure=document.createElement('figure'),span=document.createElement('span'),image=document.createElement('img');figure.className='imageblock alignCenter';image.src=j.media.publicPath;image.alt=name;image.loading='lazy';image.decoding='async';span.append(image);figure.append(span);
  const selection=window.getSelection(),savedRange=uploadRange&&$('bodyHtml').contains(uploadRange.commonAncestorContainer)?uploadRange:selection.rangeCount&&$('bodyHtml').contains(selection.getRangeAt(0).commonAncestorContainer)?selection.getRangeAt(0):null;if(savedRange){savedRange.deleteContents();savedRange.insertNode(figure);savedRange.setStartAfter(figure);savedRange.collapse(true);selection.removeAllRanges();selection.addRange(savedRange);uploadRange=savedRange.cloneRange()}else{$('bodyHtml').append(figure);uploadRange=document.createRange();uploadRange.setStartAfter(figure);uploadRange.collapse(true)}uploadQueue.shift();if(!uploadQueue.length)$('image').value='';
  clearMediaSelection();rememberEditorChange();dirty=true;change+=1;renderSaveState();if(!await flush()){if(uploadQueue.length)retryAction=uploadImage;return}}
  uploadRange=null;$('uploadPanel').hidden=true;$('image').value='';status('사진을 본문에 넣고 작업본에 저장했습니다.');
}
$('upload').onclick=()=>action(uploadImage);
$('retrySave').onclick=async()=>{const retry=retryAction||flush;await action(async()=>{clearIssue();await retry();if(!blocked&&dirty)await flush()});if(!blocked)await followAdminDeepLink()};
$('resumeLogin').onclick=async()=>{const retry=retryAction||flush;await action(async()=>{try{await list()}catch(error){showIssue(error,retry);return}clearIssue();await retry();if(!blocked&&dirty)await flush();if(!blocked)status('로그인을 확인했습니다. 작성 내용을 이어서 처리했습니다.')});if(!blocked)await followAdminDeepLink()};
$('loadLatest').onclick=()=>action(async()=>{if(!current)return;const post=(await api('/posts/'+encodeURIComponent(current.id))).post;fill(post);status('최신 작업본을 불러왔습니다. 이전에 이 화면에서 작성한 내용 대신 표시합니다.')});
$('keepLocal').onclick=()=>action(async()=>{
  if(!current)return;const latest=(await api('/posts/'+encodeURIComponent(current.id))).post;
  current={...latest,coverMediaId:current.coverMediaId,coverPath:current.coverPath,coverAlt:current.coverAlt};updateCoverSummary();dirty=true;blocked='review';retryAction=async()=>{await flush()};$('issueMessage').textContent='현재 작성 내용은 그대로 유지했습니다. 아래 버튼을 누르면 다른 곳에서 저장한 최신 작업본을 현재 작성 내용으로 바꿉니다. 공개 글은 공개 반영 전까지 바뀌지 않습니다.';$('retrySave').textContent='현재 작성본으로 저장';$('retrySave').hidden=false;$('loadLatest').hidden=false;$('keepLocal').hidden=true;$('loginLink').hidden=true;$('resumeLogin').hidden=true;renderSaveState();
});
window.addEventListener('beforeunload',event=>{if(dirty||saving||busy||hasManagementChanges()){event.preventDefault();event.returnValue=''}});
${editorHistoryScript}
${formattingScript}
${autoLinkScript}
${managementScript}
${statisticsScript}
${adminNavigationScript}
${publishingScript}
${extrasScript}
${imageLayoutScript}
${imageDirectScript}
const mountEngineDiagram=${mountEngineDiagram.toString()};
setView('list');
void(async()=>{await action(async()=>{await loadCategories();await loadSiteTimezone();await list()});adminReady=true;await followAdminDeepLink()})();

</script></body></html>`;
}
