import { FONT_SIZE_PRESET_OPTIONS, fontSizePresetScript } from './body-typography.ts';
import { htmlPasteDetectorScript } from './html-source-paste.ts';
import { extrasToolbarHtml } from './admin-extras.ts';
// Keep browser editing commands in the existing contenteditable surface so that
// imported image, card and table markup outside the selection stays intact.
export const formattingCss = `
.format-toolbar{display:flex;align-items:center;flex-wrap:nowrap;gap:0;padding:0;background:#fff;overflow-x:auto;overscroll-behavior-x:contain;scrollbar-width:thin;min-width:0;max-width:100%}
.format-group{display:flex;gap:2px;align-items:center;padding:0 9px;border-right:1px solid #e6e7e9;flex-shrink:0}.format-group:first-child{padding-left:0}.format-group:last-child{border-right:0;padding-right:0}
.format-toolbar button{min-width:30px;min-height:32px;padding:5px 6px;color:#45494f;background:#fff;border:1px solid transparent;border-radius:3px;font-size:13px;line-height:1}.format-toolbar button:hover{background:#f1f3f5}.format-toolbar button[aria-pressed="true"]{background:#edf2f8;border-color:#d2dfed;color:#155c9d}.format-toolbar button svg{display:block;width:17px;height:17px}
.format-toolbar button:focus-visible,.format-toolbar select:focus-visible,.format-toolbar input:focus-visible{outline:2px solid #1264d1;outline-offset:-2px}.format-toolbar label{display:flex;gap:3px;align-items:center;font-size:11px;font-weight:400;margin:0;color:#666}.format-toolbar select{width:auto;max-width:100px;padding:5px 3px;font-size:12px;min-height:32px;border-color:transparent;background:#fff}.format-toolbar input[type="color"]{width:23px;height:25px;padding:1px;border:1px solid #e0e2e5;border-radius:3px}
.format-panel{position:fixed;top:calc(var(--editor-header-height,72px) + 10px);left:50%;transform:translateX(-50%);z-index:40;width:min(650px,calc(100vw - 32px));max-height:60vh;overflow:auto;padding:18px;background:#fff;border:1px solid #d6dbe1;border-radius:6px;box-shadow:0 5px 22px #0002}.format-panel label{margin:4px 0;font-size:13px}.format-panel .row{align-items:flex-end}.format-panel input[type="number"]{max-width:90px}.format-panel p{margin:10px 0;font-size:12px;color:#777}.format-panel button{font-size:13px}
.html-editor{font-size:var(--dwnc-body-size,18px);line-height:1.8;overflow-wrap:anywhere}.html-editor p{margin:.5em 0}.html-editor :is(h2,h3,h4){line-height:1.35}.html-editor h2{font-size:calc(var(--dwnc-body-size,18px)*2)}.html-editor h3{font-size:calc(var(--dwnc-body-size,18px)*1.5)}.html-editor h4{font-size:calc(var(--dwnc-body-size,18px)*1.2)}.html-editor blockquote{margin:1em 0;padding:.3em 1em;border-left:3px solid #b47955;background:#faf8f3}.html-editor table{border-collapse:collapse;max-width:100%}.html-editor :is(td,th){min-width:40px;padding:8px;border:1px solid #aaa}.html-editor hr{border:0;border-top:1px solid #aaa;margin:1.4em 0}.html-editor a{color:#165ba8;text-decoration:underline}.html-editor :is(ul,ol){padding-left:1.8em}.format-toolbar[hidden],.format-panel[hidden],#body[hidden],#markdownMedia[hidden]{display:none}
@media(max-width:760px){.format-group{padding:0 8px}.format-toolbar{padding:3px 0 5px}.format-toolbar button{min-width:31px;min-height:33px}.format-toolbar select{max-width:94px}}
`;

export const formattingToolbarHtml = `
<div id="formatToolbar" class="format-toolbar" role="toolbar" aria-label="본문 서식">
${extrasToolbarHtml}
<div class="format-group"><button id="openImageLayout" type="button">사진 배치</button></div>
 <div class="format-group"><select id="formatBlock" aria-label="문단 스타일"><option value="p">본문</option><option value="h2">큰 제목</option><option value="h3">중간 제목</option><option value="h4">작은 제목</option></select><select id="fontSize" aria-label="글자 크기">${FONT_SIZE_PRESET_OPTIONS}</select></div>
 <div class="format-group"><button type="button" data-format-command="bold" aria-label="굵게" title="굵게 (⌘/Ctrl+B)" aria-pressed="false"><b>B</b></button><button type="button" data-format-command="italic" aria-label="기울임" title="기울임 (⌘/Ctrl+I)" aria-pressed="false"><i>I</i></button><button type="button" data-format-command="underline" aria-label="밑줄" title="밑줄 (⌘/Ctrl+U)" aria-pressed="false"><u>U</u></button><button type="button" data-format-command="strikeThrough" aria-label="취소선" title="취소선" aria-pressed="false"><s>S</s></button></div>
 <div class="format-group"><label>글자색<input id="textColor" type="color" value="#222222" aria-label="글자색"></label><label>배경색<input id="highlightColor" type="color" value="#fff2a8" aria-label="글자 배경색"></label></div>
 <div class="format-group"><button type="button" data-format-command="justifyLeft" aria-label="왼쪽 정렬" title="왼쪽 정렬"><svg viewBox="0 0 18 18" aria-hidden="true"><path d="M2 3h14M2 7h9M2 11h14M2 15h9" fill="none" stroke="currentColor" stroke-width="1.4"/></svg></button><button type="button" data-format-command="justifyCenter" aria-label="가운데 정렬" title="가운데 정렬"><svg viewBox="0 0 18 18" aria-hidden="true"><path d="M2 3h14M5 7h8M2 11h14M5 15h8" fill="none" stroke="currentColor" stroke-width="1.4"/></svg></button><button type="button" data-format-command="justifyRight" aria-label="오른쪽 정렬" title="오른쪽 정렬"><svg viewBox="0 0 18 18" aria-hidden="true"><path d="M2 3h14M7 7h9M2 11h14M7 15h9" fill="none" stroke="currentColor" stroke-width="1.4"/></svg></button><button type="button" data-format-command="justifyFull" aria-label="양쪽 정렬" title="양쪽 정렬"><svg viewBox="0 0 18 18" aria-hidden="true"><path d="M2 3h14M2 7h14M2 11h14M2 15h14" fill="none" stroke="currentColor" stroke-width="1.4"/></svg></button></div>
 <div class="format-group"><button type="button" data-format-command="insertUnorderedList" aria-label="글머리 목록" title="글머리 목록">• 목록</button><button type="button" data-format-command="insertOrderedList" aria-label="번호 목록" title="번호 목록">1. 목록</button><button type="button" data-format-command="blockquote" aria-label="인용" title="인용">인용</button><button type="button" data-format-command="insertHorizontalRule" aria-label="구분선" title="구분선">―</button></div>
 <div class="format-group"><button id="editLink" type="button" title="링크 삽입·수정 (⌘/Ctrl+K)">링크</button><button id="insertTable" type="button" title="표 삽입">표</button></div>
 <div class="format-group"><button type="button" data-format-command="undo" aria-label="실행 취소" title="실행 취소 (⌘/Ctrl+Z)">↶</button><button type="button" data-format-command="redo" aria-label="다시 실행" title="다시 실행 (⌘/Ctrl+Shift+Z)">↷</button></div>
</div>
<div id="linkPanel" class="format-panel" hidden><div class="row"><label class="grow">링크 주소<input id="linkUrl" type="url" placeholder="https://example.com 또는 /posts/597"></label><label class="grow">표시할 글자<input id="linkText"></label></div><p id="linkHint">본문의 글자를 선택하거나 기존 링크에 커서를 놓고 사용할 수 있습니다.</p><div class="row"><button id="applyLink" type="button">링크 적용</button><button id="removeLink" type="button" class="secondary">링크 해제</button><button id="cancelLink" type="button" class="secondary">닫기</button></div></div>
<div id="tablePanel" class="format-panel" hidden><div class="row"><label>행<input id="tableRows" type="number" min="1" max="10" value="2"></label><label>열<input id="tableColumns" type="number" min="1" max="10" value="2"></label><button id="applyTable" type="button">표 넣기</button><button id="cancelTable" type="button" class="secondary">닫기</button></div><p>셀 안을 눌러 글을 입력합니다. Tab 키로 다음 셀로 이동할 수 있습니다.</p></div>
`;

export const formattingScript = htmlPasteDetectorScript + String.raw`
let formatRange=null,editingLink=null,pendingFontSpans=null,pastedImageNodes=null;
function bodyRange(){const selection=window.getSelection();if(!selection||!selection.rangeCount)return null;const range=selection.getRangeAt(0);return $('bodyHtml').contains(range.commonAncestorContainer)?range:null}
function captureFormatRange(){const range=bodyRange();if(range)formatRange=range.cloneRange()}
function restoreFormatRange(){const body=$('bodyHtml');body.focus({preventScroll:true});const selection=window.getSelection();let range=formatRange;if(!range||!body.contains(range.commonAncestorContainer)){range=document.createRange();range.selectNodeContents(body);range.collapse(false)}const active=selection.rangeCount?selection.getRangeAt(0):null;if(active&&active.startContainer===range.startContainer&&active.startOffset===range.startOffset&&active.endContainer===range.endContainer&&active.endOffset===range.endOffset)return active;selection.removeAllRanges();selection.addRange(range);return range}
// queryCommandState can report the surrounding paragraph for CSS-aligned
// captions. Read the visible caption alignment without modifying saved HTML.
function captionFormatAlignment(range){
  const ancestor=range.commonAncestorContainer,element=ancestor.nodeType===1?ancestor:ancestor.parentElement;
  if(!element?.closest('figcaption,.se-caption,.se_mediaCaption'))return null;
  let node=range.startContainer;if(node.nodeType===1)node=node.childNodes[range.startOffset]||node;
  const selected=node.nodeType===1?node:node.parentElement,style=window.getComputedStyle(selected),align=style.textAlign;
  return align==='start'?(style.direction==='rtl'?'right':'left'):align==='end'?(style.direction==='rtl'?'left':'right'):align;
}
function updateFormatState(){const range=bodyRange();if(!range)return;const captionAlign=captionFormatAlignment(range),alignments={justifyLeft:'left',justifyCenter:'center',justifyRight:'right',justifyFull:'justify'};for(const button of $('formatToolbar').querySelectorAll('[data-format-command]')){const cmd=button.dataset.formatCommand;if(['bold','italic','underline','strikeThrough','insertUnorderedList','insertOrderedList','justifyLeft','justifyCenter','justifyRight','justifyFull'].includes(cmd)){try{button.setAttribute('aria-pressed',String(captionAlign&&alignments[cmd]?captionAlign===alignments[cmd]:document.queryCommandState(cmd)))}catch{}}}try{const block=String(document.queryCommandValue('formatBlock')).toLowerCase();$('formatBlock').value=['h2','h3','h4'].includes(block)?block:'p';showCurrentFontSize(range)}catch{}}
${fontSizePresetScript}
function showCurrentFontSize(range){let node=range.startContainer;if(node.nodeType===1)node=node.childNodes[range.startOffset]||node.childNodes[range.startOffset-1]||node;while(node.nodeType===1&&node.firstChild)node=node.firstChild;const element=node.nodeType===1?node:node.parentElement;if(!element)return;const actual=window.getComputedStyle(element).fontSize,old=$('fontSize').querySelector('option[value="current"]');let own=element;while(own&&own!==$('bodyHtml')&&!own.style.fontSize&&!own.getAttribute('size'))own=own.parentElement;const marker=own?.style.fontSize.match(/--dwnc-text-size-([1-7])/),preset=marker?.[1]||(!own?.style.fontSize&&!own?.getAttribute('size')&&actual==='18px'?'3':null);if(preset){$('fontSize').value=preset;if(old)old.remove()}else{const option=old||document.createElement('option');option.value='current';option.disabled=true;option.textContent=actual||'기존 크기';if(!old)$('fontSize').append(option);$('fontSize').value='current'}}
function closeFormatPanels(){closeExtraMenu();$('linkPanel').hidden=true;$('tablePanel').hidden=true;editingLink=null}
function resetFormatting(){clearPlainPasteIntent();formatRange=null;pendingFontSpans=null;pastedImageNodes=null;closeFormatPanels();$('formatBlock').value='p';$('fontSize').value='3';$('fontFamily').value='current';for(const b of $('formatToolbar').querySelectorAll('[aria-pressed]'))b.setAttribute('aria-pressed','false')}
function setFormattingBusy(value){for(const panel of ['formatToolbar','linkPanel','tablePanel'])for(const node of $(panel).querySelectorAll('button,input,select'))node.disabled=value;if(!value&&!editingLink)$('removeLink').disabled=true}
function markChangedFontSpans(before,preset=null){const range=bodyRange()||formatRange;if(!range)return;for(const span of $('bodyHtml').querySelectorAll('span[style]')){if(span.style.fontSize&&(!before.has(span)||before.get(span)!==span.style.fontSize)&&range.intersectsNode(span))span.style.setProperty('font-size',sizePresetValue(preset)||span.style.fontSize,'important')}}
function textFormattingAvailable(){if(selectedMedia){status('이미지나 링크 카드 대신 서식을 바꿀 본문 글자를 선택하세요.');return false}return true}
function formatCommand(command,value=null){
  if(busy||!current)return false;if(['undo','redo'].includes(command))return editorHistoryCommand(command);if(!textFormattingAvailable())return false;restoreFormatRange();captureEditorBefore();editorTyping=null;const before=$('bodyHtml').innerHTML,fontSpans=command==='fontSize'?new Map(Array.from($('bodyHtml').querySelectorAll('span[style]'),span=>[span,span.style.fontSize])):null,collapsed=bodyRange()?.collapsed;
  if(command==='fontSize'||command==='undo'||command==='redo'||!collapsed)pendingFontSpans=null;
  try{if(!['undo','redo'].includes(command))document.execCommand('styleWithCSS',false,true);const result=document.execCommand(command,false,value);captureFormatRange();if(fontSpans){markChangedFontSpans(fontSpans);if(collapsed)pendingFontSpans=fontSpans}updateFormatState();if(command==='fontSize'&&collapsed)$('fontSize').value=String(value);if($('bodyHtml').innerHTML!==before)schedule();return result}catch{status('이 위치에는 서식을 적용할 수 없습니다. 본문 글자를 선택한 뒤 다시 시도하세요.');return false}
}

function selectedLink(){const range=bodyRange()||formatRange;if(!range)return null;const element=range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement;const link=element?.closest('a');return link&&$('bodyHtml').contains(link)&&!link.closest('figure[data-ke-type="opengraph"],.se_component.se_oglink,.se-component.se-oglink')?link:null}
function openLinkPanel(){if(busy||!current||!textFormattingAvailable())return;captureFormatRange();editingLink=selectedLink();$('tablePanel').hidden=true;$('linkPanel').hidden=false;$('linkUrl').value=editingLink?.getAttribute('href')||'';$('linkText').value=editingLink?.textContent||formatRange?.toString()||'';$('removeLink').disabled=!editingLink;$('linkHint').textContent='https:// 주소 또는 /posts/597 같은 사이트 안 주소를 입력하세요.';$('linkUrl').focus()}
function escapeFormatText(value){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function validLink(value){if(value.startsWith('/')&&!value.startsWith('//')&&!value.includes(String.fromCharCode(92)))return true;try{return ['https:','http:','mailto:'].includes(new URL(value).protocol)}catch{return false}}
for(const button of $('formatToolbar').querySelectorAll('[data-format-command]')){button.addEventListener('mousedown',event=>event.preventDefault());button.onclick=()=>{const cmd=button.dataset.formatCommand;closeFormatPanels();if(cmd==='blockquote')formatCommand('formatBlock','blockquote');else formatCommand(cmd)}}
for(const id of ['formatBlock','fontSize','textColor','highlightColor'])$(id).addEventListener('pointerdown',captureFormatRange);
$('formatBlock').onchange=()=>formatCommand('formatBlock',$('formatBlock').value);
$('fontSize').onchange=()=>{if($('fontSize').value!=='current')applyFontSizePreset($('fontSize').value)};
$('textColor').onchange=()=>formatCommand('foreColor',$('textColor').value);
$('highlightColor').onchange=()=>formatCommand('hiliteColor',$('highlightColor').value);
$('editLink').addEventListener('mousedown',event=>event.preventDefault());$('editLink').onclick=openLinkPanel;
$('cancelLink').onclick=()=>{closeFormatPanels();restoreFormatRange()};
$('applyLink').onclick=()=>{
  if(busy)return;const href=$('linkUrl').value.trim(),label=$('linkText').value;
  if(!href||!validLink(href)){$('linkHint').textContent='사용할 수 있는 링크 주소를 입력하세요. 예: https://example.com';$('linkUrl').focus();return}
  restoreFormatRange();const existing=editingLink&&$('bodyHtml').contains(editingLink)?editingLink:null;
  if(existing){const range=document.createRange();if(label===existing.textContent)range.selectNodeContents(existing);else range.selectNode(existing);formatRange=range}
  const preserveText=formatRange&&!formatRange.collapsed&&label===formatRange.toString();
  if(preserveText){formatCommand('createLink',href);const range=bodyRange();if(range){for(const link of $('bodyHtml').querySelectorAll('a[href]')){if(range.intersectsNode(link)&&link.getAttribute('href')===href){if(/^https?:/i.test(href)){link.setAttribute('target','_blank');link.setAttribute('rel','noopener noreferrer')}else{link.removeAttribute('target');link.removeAttribute('rel')}}}}}
  else{const external=/^https?:/i.test(href)?' target="_blank" rel="noopener noreferrer"':'';formatCommand('insertHTML','<a href="'+escapeFormatText(href)+'"'+external+'>'+escapeFormatText(label||href)+'</a>')}
  closeFormatPanels();
};
$('removeLink').onclick=()=>{if(busy||!editingLink)return;removeEditorLink(editingLink);closeFormatPanels()};
$('insertTable').addEventListener('mousedown',event=>event.preventDefault());$('insertTable').onclick=()=>{if(busy||!current||!textFormattingAvailable())return;captureFormatRange();closeFormatPanels();$('tablePanel').hidden=false;$('tableRows').focus()};
$('cancelTable').onclick=()=>{closeFormatPanels();restoreFormatRange()};
$('applyTable').onclick=()=>{if(busy)return;const rows=Number($('tableRows').value),columns=Number($('tableColumns').value);if(!Number.isInteger(rows)||rows<1||rows>10||!Number.isInteger(columns)||columns<1||columns>10){status('표는 행과 열을 각각 1부터 10 사이로 입력하세요.');return}let html='<table><tbody>';for(let row=0;row<rows;row++)html+='<tr>'+Array(columns).fill('<td><br></td>').join('')+'</tr>';html+='</tbody></table><p><br></p>';formatCommand('insertHTML',html);closeFormatPanels()};
$('bodyHtml').addEventListener('pointerup',discardPendingFontSizeAfterMove);
$('bodyHtml').addEventListener('keyup',event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','Escape'].includes(event.key))discardPendingFontSizeAfterMove()});
$('bodyHtml').addEventListener('beforeinput',event=>{if(!event.isComposing)discardPendingFontSizeAfterMove()});
$('bodyHtml').addEventListener('compositionend',()=>{if(pendingFontSpans){markChangedFontSpans(pendingFontSpans.before||pendingFontSpans,pendingFontSpans.preset);pendingFontSpans=null;schedule()}});
let plainPasteIntent=null;
function clearPlainPasteIntent(){plainPasteIntent=null}
$('bodyHtml').addEventListener('keydown',event=>{clearPlainPasteIntent();if(current&&!busy&&!event.isComposing&&event.keyCode!==229&&(event.metaKey||event.ctrlKey)&&event.shiftKey&&(event.code==='KeyV'||event.key.toLowerCase()==='v'))plainPasteIntent={postId:current.id,expires:Date.now()+1500}});
for(const type of ['keyup','blur','pointerdown'])$('bodyHtml').addEventListener(type,clearPlainPasteIntent);
window.addEventListener('blur',clearPlainPasteIntent);
function pasteHtmlSource(source){if(!current||busy)return;captureEditorBefore();editorTyping=null;const postId=current.id;let range=bodyRange()?.cloneRange();if(!range){range=document.createRange();range.selectNodeContents($('bodyHtml'));range.collapse(false)}return action(async()=>{let markup=null,omitted=false;try{const result=await api('/html-paste',{method:'POST',body:JSON.stringify({html:source})});markup=result.html;omitted=result.omitted}catch{status('서식으로 바꾸지 못해 원문을 글자로 붙여넣었습니다. 연결과 로그인을 확인한 뒤 다시 붙여넣을 수 있습니다.')}if(current?.id!==postId)return;const fragment=markup===null?document.createTextNode(source):range.createContextualFragment(markup),last=fragment.lastChild||fragment;range.deleteContents();range.insertNode(fragment);if(last.parentNode){range.setStartAfter(last);range.collapse(true);formatRange=range.cloneRange();const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range)}clearMediaSelection();schedule(true);if(markup!==null)status(omitted?'HTML 서식을 붙여넣었습니다. 실행 코드와 사진 등 지원하지 않는 요소는 제외했습니다.':'HTML 서식을 붙여넣었습니다. 작업본에 자동저장됩니다.')})}
$('bodyHtml').addEventListener('paste',event=>{const plainOnly=plainPasteIntent?.postId===current?.id&&plainPasteIntent?.expires>=Date.now();clearPlainPasteIntent();if(busy){event.preventDefault();return}if(plainOnly){pastedImageNodes=null;if(!event.clipboardData?.getData('text/plain'))event.preventDefault();return}const files=clipboardImages(event.clipboardData);if(files.length){event.preventDefault();return pasteImages(files,event.clipboardData?.getData('text/plain')||'')}const plain=event.clipboardData?.getData('text/plain')||'';if(isHtmlSourcePaste(plain)){event.preventDefault();return pasteHtmlSource(plain)}pastedImageNodes=new Set($('bodyHtml').querySelectorAll('img'))});
$('bodyHtml').addEventListener('input',event=>{if(pendingFontSpans&&!event.isComposing){markChangedFontSpans(pendingFontSpans.before||pendingFontSpans,pendingFontSpans.preset);pendingFontSpans=null}if(pastedImageNodes){let removed=false;for(const image of $('bodyHtml').querySelectorAll('img')){if(pastedImageNodes.has(image))continue;const src=image.getAttribute('src')||'',legacy=current?.sourceKind==='legacy',allowed=legacy?src.startsWith('/media/')||/^https?:\/\//i.test(src):/^\/media\/native\/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}\.(?:avif|gif|jpe?g|png|webp)$/i.test(src);if(!allowed){image.remove();removed=true}}pastedImageNodes=null;if(removed)status('글자와 서식은 붙여넣었습니다. 함께 복사한 사진은 저장할 수 없어 제외했습니다. 사진은 상단 사진 첨부 버튼으로 넣어 주세요.')}captureFormatRange();updateFormatState()});
document.addEventListener('selectionchange',()=>{if(bodyRange()){captureFormatRange();updateFormatState()}});
$('bodyHtml').addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openLinkPanel()}if(event.key==='Tab'){const range=bodyRange(),element=range&&(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement),cell=element?.closest('td,th');if(cell){const table=cell.closest('table'),cells=Array.from(table.querySelectorAll('td,th')),index=cells.indexOf(cell),next=cells[index+(event.shiftKey?-1:1)];if(next){event.preventDefault();const nextRange=document.createRange();nextRange.selectNodeContents(next);nextRange.collapse(true);formatRange=nextRange;restoreFormatRange()}}}});
for(const panel of ['linkPanel','tablePanel'])$(panel).addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeFormatPanels();restoreFormatRange()}else if(event.key==='Enter'&&event.target instanceof HTMLInputElement){event.preventDefault();$(panel==='linkPanel'?'applyLink':'applyTable').click()}});
function positionFormatToolbar(){const root=document.documentElement;root.style.setProperty('--editor-header-height',Math.ceil($('editorHeader').getBoundingClientRect().height)+'px');root.style.setProperty('--editor-footer-height',($('editorFooter').hidden?0:Math.ceil($('editorFooter').getBoundingClientRect().height))+'px')}
window.addEventListener('resize',positionFormatToolbar);positionFormatToolbar();if(typeof ResizeObserver!=='undefined'){const formatObserver=new ResizeObserver(positionFormatToolbar);formatObserver.observe($('editorHeader'));formatObserver.observe($('editorFooter'))}
`;
